// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package product

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddImages provides a mock function for the type MockRepository
func (_mock *MockRepository) AddImages(ctx context.Context, images []*ImageModel, id int) error {
	ret := _mock.Called(ctx, images, id)

	if len(ret) == 0 {
		panic("no return value specified for AddImages")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*ImageModel, int) error); ok {
		r0 = returnFunc(ctx, images, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_AddImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddImages'
type MockRepository_AddImages_Call struct {
	*mock.Call
}

// AddImages is a helper method to define mock.On call
//   - ctx context.Context
//   - images []*ImageModel
//   - id int
func (_e *MockRepository_Expecter) AddImages(ctx interface{}, images interface{}, id interface{}) *MockRepository_AddImages_Call {
	return &MockRepository_AddImages_Call{Call: _e.mock.On("AddImages", ctx, images, id)}
}

func (_c *MockRepository_AddImages_Call) Run(run func(ctx context.Context, images []*ImageModel, id int)) *MockRepository_AddImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*ImageModel
		if args[1] != nil {
			arg1 = args[1].([]*ImageModel)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_AddImages_Call) Return(err error) *MockRepository_AddImages_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_AddImages_Call) RunAndReturn(run func(ctx context.Context, images []*ImageModel, id int) error) *MockRepository_AddImages_Call {
	_c.Call.Return(run)
	return _c
}

// AddOption provides a mock function for the type MockRepository
func (_mock *MockRepository) AddOption(ctx context.Context, option *OptionModel, id int) (*OptionModel, error) {
	ret := _mock.Called(ctx, option, id)

	if len(ret) == 0 {
		panic("no return value specified for AddOption")
	}

	var r0 *OptionModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *OptionModel, int) (*OptionModel, error)); ok {
		return returnFunc(ctx, option, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *OptionModel, int) *OptionModel); ok {
		r0 = returnFunc(ctx, option, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*OptionModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *OptionModel, int) error); ok {
		r1 = returnFunc(ctx, option, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_AddOption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOption'
type MockRepository_AddOption_Call struct {
	*mock.Call
}

// AddOption is a helper method to define mock.On call
//   - ctx context.Context
//   - option *OptionModel
//   - id int
func (_e *MockRepository_Expecter) AddOption(ctx interface{}, option interface{}, id interface{}) *MockRepository_AddOption_Call {
	return &MockRepository_AddOption_Call{Call: _e.mock.On("AddOption", ctx, option, id)}
}

func (_c *MockRepository_AddOption_Call) Run(run func(ctx context.Context, option *OptionModel, id int)) *MockRepository_AddOption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *OptionModel
		if args[1] != nil {
			arg1 = args[1].(*OptionModel)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_AddOption_Call) Return(optionModel *OptionModel, err error) *MockRepository_AddOption_Call {
	_c.Call.Return(optionModel, err)
	return _c
}

func (_c *MockRepository_AddOption_Call) RunAndReturn(run func(ctx context.Context, option *OptionModel, id int) (*OptionModel, error)) *MockRepository_AddOption_Call {
	_c.Call.Return(run)
	return _c
}

// AddVariant provides a mock function for the type MockRepository
func (_mock *MockRepository) AddVariant(ctx context.Context, variant *VariantModel, id int) (*VariantModel, error) {
	ret := _mock.Called(ctx, variant, id)

	if len(ret) == 0 {
		panic("no return value specified for AddVariant")
	}

	var r0 *VariantModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *VariantModel, int) (*VariantModel, error)); ok {
		return returnFunc(ctx, variant, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *VariantModel, int) *VariantModel); ok {
		r0 = returnFunc(ctx, variant, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*VariantModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *VariantModel, int) error); ok {
		r1 = returnFunc(ctx, variant, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_AddVariant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddVariant'
type MockRepository_AddVariant_Call struct {
	*mock.Call
}

// AddVariant is a helper method to define mock.On call
//   - ctx context.Context
//   - variant *VariantModel
//   - id int
func (_e *MockRepository_Expecter) AddVariant(ctx interface{}, variant interface{}, id interface{}) *MockRepository_AddVariant_Call {
	return &MockRepository_AddVariant_Call{Call: _e.mock.On("AddVariant", ctx, variant, id)}
}

func (_c *MockRepository_AddVariant_Call) Run(run func(ctx context.Context, variant *VariantModel, id int)) *MockRepository_AddVariant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *VariantModel
		if args[1] != nil {
			arg1 = args[1].(*VariantModel)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_AddVariant_Call) Return(variantModel *VariantModel, err error) *MockRepository_AddVariant_Call {
	_c.Call.Return(variantModel, err)
	return _c
}

func (_c *MockRepository_AddVariant_Call) RunAndReturn(run func(ctx context.Context, variant *VariantModel, id int) (*VariantModel, error)) *MockRepository_AddVariant_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, product *Model) (*Model, error) {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *Model
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Model) (*Model, error)); ok {
		return returnFunc(ctx, product)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Model) *Model); ok {
		r0 = returnFunc(ctx, product)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Model)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *Model) error); ok {
		r1 = returnFunc(ctx, product)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - product *Model
func (_e *MockRepository_Expecter) Create(ctx interface{}, product interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, product)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, product *Model)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Model
		if args[1] != nil {
			arg1 = args[1].(*Model)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(model *Model, err error) *MockRepository_Create_Call {
	_c.Call.Return(model, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, product *Model) (*Model, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository) Delete(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(err error) *MockRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeleteImageURL provides a mock function for the type MockRepository
func (_mock *MockRepository) GetDeleteImageURL(ctx context.Context, id int) (string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDeleteImageURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetDeleteImageURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeleteImageURL'
type MockRepository_GetDeleteImageURL_Call struct {
	*mock.Call
}

// GetDeleteImageURL is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepository_Expecter) GetDeleteImageURL(ctx interface{}, id interface{}) *MockRepository_GetDeleteImageURL_Call {
	return &MockRepository_GetDeleteImageURL_Call{Call: _e.mock.On("GetDeleteImageURL", ctx, id)}
}

func (_c *MockRepository_GetDeleteImageURL_Call) Run(run func(ctx context.Context, id int)) *MockRepository_GetDeleteImageURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetDeleteImageURL_Call) Return(s string, err error) *MockRepository_GetDeleteImageURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRepository_GetDeleteImageURL_Call) RunAndReturn(run func(ctx context.Context, id int) (string, error)) *MockRepository_GetDeleteImageURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetUploadImageURL provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUploadImageURL(ctx context.Context) (*UploadImageURLModel, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUploadImageURL")
	}

	var r0 *UploadImageURLModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*UploadImageURLModel, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *UploadImageURLModel); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UploadImageURLModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetUploadImageURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUploadImageURL'
type MockRepository_GetUploadImageURL_Call struct {
	*mock.Call
}

// GetUploadImageURL is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetUploadImageURL(ctx interface{}) *MockRepository_GetUploadImageURL_Call {
	return &MockRepository_GetUploadImageURL_Call{Call: _e.mock.On("GetUploadImageURL", ctx)}
}

func (_c *MockRepository_GetUploadImageURL_Call) Run(run func(ctx context.Context)) *MockRepository_GetUploadImageURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetUploadImageURL_Call) Return(uploadImageURLModel *UploadImageURLModel, err error) *MockRepository_GetUploadImageURL_Call {
	_c.Call.Return(uploadImageURLModel, err)
	return _c
}

func (_c *MockRepository_GetUploadImageURL_Call) RunAndReturn(run func(ctx context.Context) (*UploadImageURLModel, error)) *MockRepository_GetUploadImageURL_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRepository
func (_mock *MockRepository) List(ctx context.Context, queryParams *QueryParams) (*PaginationModel, error) {
	ret := _mock.Called(ctx, queryParams)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *PaginationModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *QueryParams) (*PaginationModel, error)); ok {
		return returnFunc(ctx, queryParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *QueryParams) *PaginationModel); ok {
		r0 = returnFunc(ctx, queryParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PaginationModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *QueryParams) error); ok {
		r1 = returnFunc(ctx, queryParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - queryParams *QueryParams
func (_e *MockRepository_Expecter) List(ctx interface{}, queryParams interface{}) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, queryParams)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, queryParams *QueryParams)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *QueryParams
		if args[1] != nil {
			arg1 = args[1].(*QueryParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(paginationModel *PaginationModel, err error) *MockRepository_List_Call {
	_c.Call.Return(paginationModel, err)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(ctx context.Context, queryParams *QueryParams) (*PaginationModel, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// MoveImage provides a mock function for the type MockRepository
func (_mock *MockRepository) MoveImage(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for MoveImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MoveImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MoveImage'
type MockRepository_MoveImage_Call struct {
	*mock.Call
}

// MoveImage is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRepository_Expecter) MoveImage(ctx interface{}, key interface{}) *MockRepository_MoveImage_Call {
	return &MockRepository_MoveImage_Call{Call: _e.mock.On("MoveImage", ctx, key)}
}

func (_c *MockRepository_MoveImage_Call) Run(run func(ctx context.Context, key string)) *MockRepository_MoveImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_MoveImage_Call) Return(err error) *MockRepository_MoveImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MoveImage_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockRepository_MoveImage_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepository
func (_mock *MockRepository) Update(ctx context.Context, product *Model, id int) (*Model, error) {
	ret := _mock.Called(ctx, product, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *Model
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Model, int) (*Model, error)); ok {
		return returnFunc(ctx, product, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Model, int) *Model); ok {
		r0 = returnFunc(ctx, product, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Model)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *Model, int) error); ok {
		r1 = returnFunc(ctx, product, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - product *Model
//   - id int
func (_e *MockRepository_Expecter) Update(ctx interface{}, product interface{}, id interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, product, id)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, product *Model, id int)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Model
		if args[1] != nil {
			arg1 = args[1].(*Model)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(model *Model, err error) *MockRepository_Update_Call {
	_c.Call.Return(model, err)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(ctx context.Context, product *Model, id int) (*Model, error)) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOption provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateOption(ctx context.Context, option *OptionModel, optionId int) (*OptionModel, error) {
	ret := _mock.Called(ctx, option, optionId)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOption")
	}

	var r0 *OptionModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *OptionModel, int) (*OptionModel, error)); ok {
		return returnFunc(ctx, option, optionId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *OptionModel, int) *OptionModel); ok {
		r0 = returnFunc(ctx, option, optionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*OptionModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *OptionModel, int) error); ok {
		r1 = returnFunc(ctx, option, optionId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_UpdateOption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOption'
type MockRepository_UpdateOption_Call struct {
	*mock.Call
}

// UpdateOption is a helper method to define mock.On call
//   - ctx context.Context
//   - option *OptionModel
//   - optionId int
func (_e *MockRepository_Expecter) UpdateOption(ctx interface{}, option interface{}, optionId interface{}) *MockRepository_UpdateOption_Call {
	return &MockRepository_UpdateOption_Call{Call: _e.mock.On("UpdateOption", ctx, option, optionId)}
}

func (_c *MockRepository_UpdateOption_Call) Run(run func(ctx context.Context, option *OptionModel, optionId int)) *MockRepository_UpdateOption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *OptionModel
		if args[1] != nil {
			arg1 = args[1].(*OptionModel)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateOption_Call) Return(optionModel *OptionModel, err error) *MockRepository_UpdateOption_Call {
	_c.Call.Return(optionModel, err)
	return _c
}

func (_c *MockRepository_UpdateOption_Call) RunAndReturn(run func(ctx context.Context, option *OptionModel, optionId int) (*OptionModel, error)) *MockRepository_UpdateOption_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateVariant provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateVariant(ctx context.Context, variant *VariantModel, variantId int) (*VariantModel, error) {
	ret := _mock.Called(ctx, variant, variantId)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVariant")
	}

	var r0 *VariantModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *VariantModel, int) (*VariantModel, error)); ok {
		return returnFunc(ctx, variant, variantId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *VariantModel, int) *VariantModel); ok {
		r0 = returnFunc(ctx, variant, variantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*VariantModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *VariantModel, int) error); ok {
		r1 = returnFunc(ctx, variant, variantId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_UpdateVariant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateVariant'
type MockRepository_UpdateVariant_Call struct {
	*mock.Call
}

// UpdateVariant is a helper method to define mock.On call
//   - ctx context.Context
//   - variant *VariantModel
//   - variantId int
func (_e *MockRepository_Expecter) UpdateVariant(ctx interface{}, variant interface{}, variantId interface{}) *MockRepository_UpdateVariant_Call {
	return &MockRepository_UpdateVariant_Call{Call: _e.mock.On("UpdateVariant", ctx, variant, variantId)}
}

func (_c *MockRepository_UpdateVariant_Call) Run(run func(ctx context.Context, variant *VariantModel, variantId int)) *MockRepository_UpdateVariant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *VariantModel
		if args[1] != nil {
			arg1 = args[1].(*VariantModel)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateVariant_Call) Return(variantModel *VariantModel, err error) *MockRepository_UpdateVariant_Call {
	_c.Call.Return(variantModel, err)
	return _c
}

func (_c *MockRepository_UpdateVariant_Call) RunAndReturn(run func(ctx context.Context, variant *VariantModel, variantId int) (*VariantModel, error)) *MockRepository_UpdateVariant_Call {
	_c.Call.Return(run)
	return _c
}
