template: testify
filename: "{{ .InterfaceName | lower }}_mock.go"
packages:
  backend/internal/domain:
    config:
      include-interface-regex: "Repository$"
  backend/internal/application:
    config:
      include-interface-regex: "^(VNPayPaymentService)$"
