#:schema https://raw.githubusercontent.com/jdx/mise/refs/heads/main/schema/mise.json

[env]
# '_'.file = { path = ".env", required = false }
# _.nix = true

[tasks.build]
sources = ["./cmd/**/*.go", "./internal/**/*.go", "./pkg/**/*.go", "./go.mod"]
outputs = ["./backend"]
run = "go build -gcflags='all=-N -l' -o ./backend ./cmd/main.go"

[tasks.dev]
depends = "build"
run = "./backend"

[tools]
atlas = "0.37.0"
go = "1.25.3"
"go:github.com/cweill/gotests/gotests" = "v1.6.0"
"go:github.com/google/wire/cmd/wire" = "0.7.0"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "1.30.0"
golangci-lint = "2.5.0"
just = "latest"
swag = "1.16.6"
terraform = "1.13.4"
watchexec = "latest"
