[env]
# '_'.file = { path = ".env", required = false }
_.nix = true

[tasks.build]
sources = [
  "./cmd/**/*.go",
  "./cmd/**/*.go",
  "./internal/**/*.go",
  "./pkg/**/*.go",
  "./go.mod",
]
outputs = ["./backend"]
run = "go build -gcflags='all=-N -l' -o ./backend ./cmd/main.go"

[tasks.dev]
depends = "build"
run = "./backend"

[tools]
go = "1.25.3"
golangci-lint = "2.5.0"
just = "latest"
terraform = "1.13.4"
watchexec = "latest"
