// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package category

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ListCategories provides a mock function for the type MockRepository
func (_mock *MockRepository) ListCategories(ctx context.Context, queryParams *QueryParams) (*PaginationModel, error) {
	ret := _mock.Called(ctx, queryParams)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 *PaginationModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *QueryParams) (*PaginationModel, error)); ok {
		return returnFunc(ctx, queryParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *QueryParams) *PaginationModel); ok {
		r0 = returnFunc(ctx, queryParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PaginationModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *QueryParams) error); ok {
		r1 = returnFunc(ctx, queryParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCategories'
type MockRepository_ListCategories_Call struct {
	*mock.Call
}

// ListCategories is a helper method to define mock.On call
//   - ctx context.Context
//   - queryParams *QueryParams
func (_e *MockRepository_Expecter) ListCategories(ctx interface{}, queryParams interface{}) *MockRepository_ListCategories_Call {
	return &MockRepository_ListCategories_Call{Call: _e.mock.On("ListCategories", ctx, queryParams)}
}

func (_c *MockRepository_ListCategories_Call) Run(run func(ctx context.Context, queryParams *QueryParams)) *MockRepository_ListCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *QueryParams
		if args[1] != nil {
			arg1 = args[1].(*QueryParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListCategories_Call) Return(paginationModel *PaginationModel, err error) *MockRepository_ListCategories_Call {
	_c.Call.Return(paginationModel, err)
	return _c
}

func (_c *MockRepository_ListCategories_Call) RunAndReturn(run func(ctx context.Context, queryParams *QueryParams) (*PaginationModel, error)) *MockRepository_ListCategories_Call {
	_c.Call.Return(run)
	return _c
}
