// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attribute.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttribute = `-- name: CreateAttribute :one
INSERT INTO attributes (
  code,
  name
)
VALUES (
  $1,
  $2
)
RETURNING
  id, code, name, deleted_at
`

type CreateAttributeParams struct {
	Code string
	Name string
}

func (q *Queries) CreateAttribute(ctx context.Context, arg CreateAttributeParams) (Attribute, error) {
	row := q.db.QueryRow(ctx, createAttribute, arg.Code, arg.Name)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.DeletedAt,
	)
	return i, err
}

const createAttributeValues = `-- name: CreateAttributeValues :many
INSERT INTO attribute_values (
  attribute_id,
  value
)
SELECT
  UNNEST($1::integer[]) AS attribute_id,
  UNNEST($2::text[]) AS value
RETURNING
  id, attribute_id, value
`

type CreateAttributeValuesParams struct {
	AttributeIds []int32
	Values       []string
}

func (q *Queries) CreateAttributeValues(ctx context.Context, arg CreateAttributeValuesParams) ([]AttributeValue, error) {
	rows, err := q.db.Query(ctx, createAttributeValues, arg.AttributeIds, arg.Values)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttributeValue
	for rows.Next() {
		var i AttributeValue
		if err := rows.Scan(&i.ID, &i.AttributeID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAttribute = `-- name: DeleteAttribute :execrows
UPDATE
  attributes
SET
  deleted_at = NOW()
WHERE
  id = $1
`

type DeleteAttributeParams struct {
	ID int32
}

func (q *Queries) DeleteAttribute(ctx context.Context, arg DeleteAttributeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAttribute, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAttributeByID = `-- name: GetAttributeByID :one
SELECT
  id, code, name, deleted_at
FROM
  attributes
WHERE
  id = $1
`

type GetAttributeByIDParams struct {
	ID int32
}

func (q *Queries) GetAttributeByID(ctx context.Context, arg GetAttributeByIDParams) (Attribute, error) {
	row := q.db.QueryRow(ctx, getAttributeByID, arg.ID)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.DeletedAt,
	)
	return i, err
}

const getAttributes = `-- name: GetAttributes :many
SELECT
  id, code, name, deleted_at,
  COUNT(*) OVER() AS current_count,
  COUNT(*) AS total_count
FROM
  attributes
ORDER BY
  id ASC
OFFSET COALESCE($1::integer, 0)
LIMIT COALESCE($2::integer, 20)
`

type GetAttributesParams struct {
	Offset pgtype.Int4
	Limit  pgtype.Int4
}

type GetAttributesRow struct {
	ID           int32
	Code         string
	Name         string
	DeletedAt    pgtype.Timestamp
	CurrentCount int64
	TotalCount   int64
}

func (q *Queries) GetAttributes(ctx context.Context, arg GetAttributesParams) ([]GetAttributesRow, error) {
	rows, err := q.db.Query(ctx, getAttributes, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttributesRow
	for rows.Next() {
		var i GetAttributesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.DeletedAt,
			&i.CurrentCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttribute = `-- name: UpdateAttribute :one
UPDATE
  attributes
SET
  code = $1,
  name = $2
WHERE
  id = $3
RETURNING
  id, code, name, deleted_at
`

type UpdateAttributeParams struct {
	Code string
	Name string
	ID   int32
}

func (q *Queries) UpdateAttribute(ctx context.Context, arg UpdateAttributeParams) (Attribute, error) {
	row := q.db.QueryRow(ctx, updateAttribute, arg.Code, arg.Name, arg.ID)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.DeletedAt,
	)
	return i, err
}
