// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attribute struct {
	ID   int32
	Code string
	Name string
}

type AttributeValue struct {
	ID          int32
	AttributeID int32
	Value       string
}

type Cart struct {
	ID        int32
	userID    uuid.UUID
	UpdatedAt pgtype.Timestamp
}

type CartItem struct {
	ID               int32
	Quantity         int32
	CartID           int32
	ProductVariantID int32
}

type Category struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type Option struct {
	ID        int32
	Name      string
	ProductID int32
}

type OptionValue struct {
	ID       int32
	Value    string
	OptionID int32
}

type OptionValuesProductVariant struct {
	ProductVariantID int32
	OptionValueID    int32
}

type Order struct {
	ID        int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	userID    uuid.UUID
	StatusID  int32
	PaymentID int32
}

type OrderItem struct {
	ID               int32
	Quantity         int32
	OrderID          int32
	ProductVariantID int32
}

type OrderStatus struct {
	ID   int32
	Name string
}

type Payment struct {
	ID         int32
	Amount     pgtype.Numeric
	UpdatedAt  pgtype.Timestamp
	MethodID   int32
	StatusID   int32
	ProviderID int32
}

type PaymentMethod struct {
	ID   int32
	Name string
}

type PaymentProvider struct {
	ID   int32
	Name string
}

type PaymentStatus struct {
	ID   int32
	Name string
}

type Product struct {
	ID            int32
	Name          string
	Description   string
	ViewsCount    int32
	TotalPurchase int32
	TrendingScore float64
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	DeletedAt     pgtype.Timestamp
}

type ProductImage struct {
	ID               int32
	URL              string
	CreatedAt        pgtype.Timestamp
	Order            int32
	ProductVariantID pgtype.Int4
}

type ProductVariant struct {
	ID            int32
	SKU           string
	Price         pgtype.Numeric
	Quantity      int32
	PurchaseCount int32
	ProductID     int32
	CreatedAt     pgtype.Timestamp
	DeletedAt     pgtype.Timestamp
}

type ProductsAttributeValue struct {
	ProductID        int32
	AttributeValueID int32
}

type ProductsCategory struct {
	ProductID  int32
	CategoryID int32
}

type Refund struct {
	ID              int32
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	StatusID        int32
	PaymentID       int32
	ReturnRequestID int32
}

type RefundStatus struct {
	ID   int32
	Name string
}

type ReturnRequest struct {
	ID          int32
	Reason      string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	StatusID    int32
	userID      uuid.UUID
	OrderItemID int32
}

type ReturnRequestStatus struct {
	ID   int32
	Name string
}

type Review struct {
	ID        int32
	Rating    int32
	Content   pgtype.Text
	ImageURL  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
	userID    uuid.UUID
	ProductID int32
}

type User struct {
	ID uuid.UUID
}
