// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: option.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOption = `-- name: CreateOption :one
INSERT INTO options (
  name
)
VALUES (
  $1
)
RETURNING
  id, name, product_id, deleted_at
`

type CreateOptionParams struct {
	Name string
}

func (q *Queries) CreateOption(ctx context.Context, arg CreateOptionParams) (Option, error) {
	row := q.db.QueryRow(ctx, createOption, arg.Name)
	var i Option
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProductID,
		&i.DeletedAt,
	)
	return i, err
}

const createOptionValues = `-- name: CreateOptionValues :many
INSERT INTO option_values (
  option_id,
  value
)
SELECT
  $1,
  UNNEST($2::text[]) AS value
RETURNING
  id, value, option_id
`

type CreateOptionValuesParams struct {
	OptionID int32
	Values   []string
}

func (q *Queries) CreateOptionValues(ctx context.Context, arg CreateOptionValuesParams) ([]OptionValue, error) {
	rows, err := q.db.Query(ctx, createOptionValues, arg.OptionID, arg.Values)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OptionValue
	for rows.Next() {
		var i OptionValue
		if err := rows.Scan(&i.ID, &i.Value, &i.OptionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteOptionValues = `-- name: DeleteOptionValues :execrows
DELETE FROM
  option_values
WHERE
  id = ANY ($1::integer[])
`

type DeleteOptionValuesParams struct {
	Ids []int32
}

func (q *Queries) DeleteOptionValues(ctx context.Context, arg DeleteOptionValuesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOptionValues, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOptions = `-- name: DeleteOptions :execrows
UPDATE
  options
SET
  deleted_at = NOW()
WHERE
  id = ANY ($1::integer[])
  AND deleted_at IS NULL
`

type DeleteOptionsParams struct {
	Ids []int32
}

func (q *Queries) DeleteOptions(ctx context.Context, arg DeleteOptionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOptions, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOption = `-- name: GetOption :one
SELECT
  id, name, product_id, deleted_at
FROM
  options
WHERE
  id = $1::integer
  AND CASE
    WHEN $2::bool THEN deleted_at IS NOT NULL
    WHEN $2::bool = FALSE THEN deleted_at IS NULL
    ELSE TRUE
  END
`

type GetOptionParams struct {
	ID                 int32
	IncludeDeletedOnly pgtype.Bool
}

func (q *Queries) GetOption(ctx context.Context, arg GetOptionParams) (Option, error) {
	row := q.db.QueryRow(ctx, getOption, arg.ID, arg.IncludeDeletedOnly)
	var i Option
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProductID,
		&i.DeletedAt,
	)
	return i, err
}

const listOptions = `-- name: ListOptions :many
SELECT
  id, name, product_id, deleted_at
FROM
  options
WHERE
  CASE
    WHEN $1::integer[] IS NULL THEN TRUE
    ELSE options.id = ANY ($1::integer[])
  END
  AND CASE
    WHEN $2::integer IS NULL THEN TRUE
    ELSE options.product_id = $2::integer
  END
  AND CASE
    WHEN $3::bool THEN deleted_at IS NOT NULL
    WHEN $3::bool = FALSE THEN deleted_at IS NULL
    ELSE TRUE
  END
ORDER BY
  options.id
`

type ListOptionsParams struct {
	Ids                []int32
	ProductID          pgtype.Int4
	IncludeDeletedOnly pgtype.Bool
}

func (q *Queries) ListOptions(ctx context.Context, arg ListOptionsParams) ([]Option, error) {
	rows, err := q.db.Query(ctx, listOptions, arg.Ids, arg.ProductID, arg.IncludeDeletedOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Option
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProductID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOptionValues = `-- name: UpdateOptionValues :execrows
WITH updated_option_values AS (
  SELECT
    UNNEST($1::integer[]) AS id,
    UNNEST($2::text[]) AS value
)
UPDATE option_values
SET
  value = updated_option_values.value
FROM
  updated_option_values
WHERE
  option_values.id = updated_option_values.id
`

type UpdateOptionValuesParams struct {
	Ids    []int32
	Values []string
}

func (q *Queries) UpdateOptionValues(ctx context.Context, arg UpdateOptionValuesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOptionValues, arg.Ids, arg.Values)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOptions = `-- name: UpdateOptions :execrows
WITH updated_options AS (
  SELECT
    UNNEST($1::integer[]) AS id,
    UNNEST($2::text[]) AS name
)
UPDATE options
SET
  name = updated_options.name
FROM
  updated_options
WHERE
  options.id = updated_options.id
  AND options.deleted_at IS NULL
`

type UpdateOptionsParams struct {
	Ids   []int32
	Names []string
}

func (q *Queries) UpdateOptions(ctx context.Context, arg UpdateOptionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOptions, arg.Ids, arg.Names)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
