// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  user_id,
  status_id
) VALUES (
  $1,
  $2
)
RETURNING
  id, created_at, updated_at, user_id, status_id
`

type CreateOrderParams struct {
	userID   uuid.UUID
	StatusID int32
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.userID, arg.StatusID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.userID,
		&i.StatusID,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
  quantity,
  order_id,
  price_at_order,
  product_variant_id
) VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING
  id, quantity, order_id, price_at_order, product_variant_id
`

type CreateOrderItemParams struct {
	Quantity         int32
	OrderID          int32
	PriceAtOrder     pgtype.Numeric
	ProductVariantID int32
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.Quantity,
		arg.OrderID,
		arg.PriceAtOrder,
		arg.ProductVariantID,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.Quantity,
		&i.OrderID,
		&i.PriceAtOrder,
		&i.ProductVariantID,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT
  id, created_at, updated_at, user_id, status_id
FROM
  orders
WHERE
  id = $1
`

type GetOrderParams struct {
	ID int32
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.userID,
		&i.StatusID,
	)
	return i, err
}
