// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (
  rating,
  content,
  image_url,
  user_id,
  product_id
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING
  id, rating, content, image_url, created_at, updated_at, deleted_at, user_id, product_id
`

type CreateReviewParams struct {
	Rating    int16
	Content   pgtype.Text
	ImageURL  string
	userID    uuid.UUID
	ProductID int32
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.Rating,
		arg.Content,
		arg.ImageURL,
		arg.userID,
		arg.ProductID,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.Rating,
		&i.Content,
		&i.ImageURL,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.userID,
		&i.ProductID,
	)
	return i, err
}

const deleteReviews = `-- name: DeleteReviews :execrows
UPDATE reviews
SET
  deleted_at = NOW()
WHERE
  id = ANY($1::integer[])
  AND deleted_at IS NULL
`

type DeleteReviewsParams struct {
	IDs []int32
}

func (q *Queries) DeleteReviews(ctx context.Context, arg DeleteReviewsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReviews, arg.IDs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listReviews = `-- name: ListReviews :many
SELECT
  id, rating, content, image_url, created_at, updated_at, deleted_at, user_id, product_id,
  COUNT(*) OVER() AS current_count,
  COUNT(*) AS total_count
FROM
  reviews
WHERE
  CASE
    WHEN $1::integer[] IS NULL THEN TRUE
    ELSE id = ANY ($1::integer[])
  END
  AND CASE
    WHEN $2::integer[] IS NULL THEN TRUE
    ELSE product_id = ANY ($2::integer[])
  END
  AND CASE
    WHEN $3::text = 'exclude' THEN deleted_at IS NOT NULL
    WHEN $3::text = 'only' THEN deleted_at IS NULL
    WHEN $3::text = 'all' THEN TRUE
    ELSE FALSE
  END
ORDER BY
  created_at DESC
OFFSET COALESCE($4::integer, 0)
LIMIT COALESCE($5::integer, 10)
`

type ListReviewsParams struct {
	IDs        []int32
	ProductIDs []int32
	Deleted    string
	Offset     pgtype.Int4
	Limit      pgtype.Int4
}

type ListReviewsRow struct {
	ID           int32
	Rating       int16
	Content      pgtype.Text
	ImageURL     string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
	userID       uuid.UUID
	ProductID    int32
	CurrentCount int64
	TotalCount   int64
}

func (q *Queries) ListReviews(ctx context.Context, arg ListReviewsParams) ([]ListReviewsRow, error) {
	rows, err := q.db.Query(ctx, listReviews,
		arg.IDs,
		arg.ProductIDs,
		arg.Deleted,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsRow
	for rows.Next() {
		var i ListReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Content,
			&i.ImageURL,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.userID,
			&i.ProductID,
			&i.CurrentCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :one
UPDATE reviews
SET
  rating = COALESCE($1::integer, rating),
  content = COALESCE($2::text, content),
  image_url = COALESCE($3::text, image_url),
  updated_at = COALESCE($4::timestamp, NOW())
WHERE
  id = $5::integer
  AND deleted_at IS NULL
RETURNING
  id, rating, content, image_url, created_at, updated_at, deleted_at, user_id, product_id
`

type UpdateReviewParams struct {
	Rating    pgtype.Int4
	Content   pgtype.Text
	ImageURL  pgtype.Text
	UpdatedAt pgtype.Timestamp
	ID        int32
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReview,
		arg.Rating,
		arg.Content,
		arg.ImageURL,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.Rating,
		&i.Content,
		&i.ImageURL,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.userID,
		&i.ProductID,
	)
	return i, err
}
