// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (
  rating,
  content,
  image_url,
  user_id,
  product_id
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING
  id, rating, content, image_url, created_at, updated_at, deleted_at, user_id, product_id
`

type CreateReviewParams struct {
	Rating    int16
	Content   pgtype.Text
	ImageURL  string
	userID    uuid.UUID
	ProductID int32
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.Rating,
		arg.Content,
		arg.ImageURL,
		arg.userID,
		arg.ProductID,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.Rating,
		&i.Content,
		&i.ImageURL,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.userID,
		&i.ProductID,
	)
	return i, err
}

const deleteReviews = `-- name: DeleteReviews :execrows
UPDATE reviews
SET
  deleted_at = NOW()
WHERE
  id = ANY($1::integer[])
  AND deleted_at IS NULL
`

type DeleteReviewsParams struct {
	Ids []int32
}

func (q *Queries) DeleteReviews(ctx context.Context, arg DeleteReviewsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReviews, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getReviewsByProductID = `-- name: GetReviewsByProductID :many
SELECT
  id, rating, content, image_url, created_at, updated_at, deleted_at, user_id, product_id,
  COUNT(*) OVER() AS current_count,
  COUNT(*) AS total_count
FROM
  reviews
WHERE
  product_id = $1
  AND deleted_at IS NULL
ORDER BY
  created_at DESC
OFFSET COALESCE($2::integer, 0)
LIMIT COALESCE($3::integer, 10)
`

type GetReviewsByProductIDParams struct {
	ProductID int32
	Offset    pgtype.Int4
	Limit     pgtype.Int4
}

type GetReviewsByProductIDRow struct {
	ID           int32
	Rating       int16
	Content      pgtype.Text
	ImageURL     string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
	userID       uuid.UUID
	ProductID    int32
	CurrentCount int64
	TotalCount   int64
}

func (q *Queries) GetReviewsByProductID(ctx context.Context, arg GetReviewsByProductIDParams) ([]GetReviewsByProductIDRow, error) {
	rows, err := q.db.Query(ctx, getReviewsByProductID, arg.ProductID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReviewsByProductIDRow
	for rows.Next() {
		var i GetReviewsByProductIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Content,
			&i.ImageURL,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.userID,
			&i.ProductID,
			&i.CurrentCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
