// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attribute.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttribute = `-- name: CreateAttribute :one
INSERT INTO attributes (
  code,
  name
)
VALUES (
  $1,
  $2
)
RETURNING
  id, code, name, deleted_at
`

type CreateAttributeParams struct {
	Code string
	Name string
}

func (q *Queries) CreateAttribute(ctx context.Context, arg CreateAttributeParams) (Attribute, error) {
	row := q.db.QueryRow(ctx, createAttribute, arg.Code, arg.Name)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.DeletedAt,
	)
	return i, err
}

const createAttributeValues = `-- name: CreateAttributeValues :many
INSERT INTO attribute_values (
  attribute_id,
  value
)
SELECT
  UNNEST($1::integer[]) AS attribute_id,
  UNNEST($2::text[]) AS value
RETURNING
  id, attribute_id, value
`

type CreateAttributeValuesParams struct {
	AttributeIDs []int32
	Values       []string
}

func (q *Queries) CreateAttributeValues(ctx context.Context, arg CreateAttributeValuesParams) ([]AttributeValue, error) {
	rows, err := q.db.Query(ctx, createAttributeValues, arg.AttributeIDs, arg.Values)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttributeValue
	for rows.Next() {
		var i AttributeValue
		if err := rows.Scan(&i.ID, &i.AttributeID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAttributeValues = `-- name: DeleteAttributeValues :execrows
DELETE FROM
  attribute_values
WHERE
  id = ANY ($1::integer[])
`

type DeleteAttributeValuesParams struct {
	IDs []int32
}

func (q *Queries) DeleteAttributeValues(ctx context.Context, arg DeleteAttributeValuesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAttributeValues, arg.IDs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAttributes = `-- name: DeleteAttributes :execrows
UPDATE
  attributes
SET
  deleted_at = NOW()
WHERE
  id = ANY ($1::integer[])
`

type DeleteAttributesParams struct {
	IDs []int32
}

func (q *Queries) DeleteAttributes(ctx context.Context, arg DeleteAttributesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAttributes, arg.IDs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAttribute = `-- name: GetAttribute :one
SELECT
  id, code, name, deleted_at
FROM
  attributes
WHERE
  id = $1
`

type GetAttributeParams struct {
	ID int32
}

func (q *Queries) GetAttribute(ctx context.Context, arg GetAttributeParams) (Attribute, error) {
	row := q.db.QueryRow(ctx, getAttribute, arg.ID)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.DeletedAt,
	)
	return i, err
}

const listAttributeValues = `-- name: ListAttributeValues :many
SELECT
  id, attribute_id, value
FROM
  attribute_values
WHERE
  CASE
    WHEN $1::integer[] IS NULL THEN TRUE
    ELSE id = ANY ($1::integer[])
  END
  AND CASE
    WHEN $2::integer[] IS NULL THEN TRUE
    ELSE attribute_id = ANY ($2::integer[])
  END
ORDER BY
  id ASC
`

type ListAttributeValuesParams struct {
	IDs          []int32
	AttributeIDs []int32
}

func (q *Queries) ListAttributeValues(ctx context.Context, arg ListAttributeValuesParams) ([]AttributeValue, error) {
	rows, err := q.db.Query(ctx, listAttributeValues, arg.IDs, arg.AttributeIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttributeValue
	for rows.Next() {
		var i AttributeValue
		if err := rows.Scan(&i.ID, &i.AttributeID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttributes = `-- name: ListAttributes :many
SELECT
  id, code, name, deleted_at,
  COUNT(*) OVER() AS current_count,
  COUNT(*) AS total_count
FROM
  attributes
WHERE
  CASE
    WHEN $1::integer[] IS NULL THEN TRUE
    ELSE id = ANY ($1::integer[])
  END
  AND CASE
    WHEN $2::text IS NULL THEN TRUE
    ELSE
      code ||| ($2::text)::pdb.fuzzy(2)
      OR name ||| ($2::text)::pdb.fuzzy(2)
  END
  AND CASE
    WHEN $3::text = 'exclude' THEN deleted_at IS NOT NULL
    WHEN $3::text = 'only' THEN deleted_at IS NULL
    WHEN $3::text = 'all' THEN TRUE
    ELSE FALSE
  END
ORDER BY
  CASE WHEN $2::text IS NOT NULL THEN pdb.score(id) END DESC,
  id ASC
OFFSET COALESCE($4::integer, 0)
LIMIT COALESCE($5::integer, 20)
`

type ListAttributesParams struct {
	IDs     []int32
	Search  pgtype.Text
	Deleted string
	Offset  pgtype.Int4
	Limit   pgtype.Int4
}

type ListAttributesRow struct {
	ID           int32
	Code         string
	Name         string
	DeletedAt    pgtype.Timestamp
	CurrentCount int64
	TotalCount   int64
}

func (q *Queries) ListAttributes(ctx context.Context, arg ListAttributesParams) ([]ListAttributesRow, error) {
	rows, err := q.db.Query(ctx, listAttributes,
		arg.IDs,
		arg.Search,
		arg.Deleted,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttributesRow
	for rows.Next() {
		var i ListAttributesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.DeletedAt,
			&i.CurrentCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsAttributeValues = `-- name: ListProductsAttributeValues :many
SELECT
  product_id, attribute_value_id
FROM
  products_attribute_values
WHERE
  CASE
    WHEN $1::integer[] IS NULL THEN TRUE
    ELSE product_variant_id = ANY ($1::integer[])
  END
  AND CASE
    WHEN $2::integer[] IS NULL THEN TRUE
    ELSE attribute_value_id = ANY ($2::integer[])
  END
`

type ListProductsAttributeValuesParams struct {
	ProductVariantIDs []int32
	AttributeValueIDs []int32
}

func (q *Queries) ListProductsAttributeValues(ctx context.Context, arg ListProductsAttributeValuesParams) ([]ProductsAttributeValue, error) {
	rows, err := q.db.Query(ctx, listProductsAttributeValues, arg.ProductVariantIDs, arg.AttributeValueIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductsAttributeValue
	for rows.Next() {
		var i ProductsAttributeValue
		if err := rows.Scan(&i.ProductID, &i.AttributeValueID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttribute = `-- name: UpdateAttribute :one
UPDATE
  attributes
SET
  code = COALESCE($1::varchar(100), code),
  name = COALESCE($2::text, name)
WHERE
  id = $3
RETURNING
  id, code, name, deleted_at
`

type UpdateAttributeParams struct {
	Code pgtype.Text
	Name pgtype.Text
	ID   int32
}

func (q *Queries) UpdateAttribute(ctx context.Context, arg UpdateAttributeParams) (Attribute, error) {
	row := q.db.QueryRow(ctx, updateAttribute, arg.Code, arg.Name, arg.ID)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.DeletedAt,
	)
	return i, err
}

const updateAttributeValues = `-- name: UpdateAttributeValues :many
WITH updated_attribute_values AS (
  SELECT
    UNNEST($1::integer[]) AS id,
    UNNEST($2::text[]) AS value
)
UPDATE
  attribute_values
SET
  value = COALESCE(updated_attribute_values.value, attribute_values.value)
FROM
  updated_attribute_values
WHERE
  attribute_values.id = updated_attribute_values.id
RETURNING
  attribute_values.id, attribute_values.attribute_id, attribute_values.value
`

type UpdateAttributeValuesParams struct {
	IDs    []int32
	Values []string
}

func (q *Queries) UpdateAttributeValues(ctx context.Context, arg UpdateAttributeValuesParams) ([]AttributeValue, error) {
	rows, err := q.db.Query(ctx, updateAttributeValues, arg.IDs, arg.Values)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttributeValue
	for rows.Next() {
		var i AttributeValue
		if err := rows.Scan(&i.ID, &i.AttributeID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
