// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attribute struct {
	ID        uuid.UUID
	Code      string
	Name      string
	DeletedAt pgtype.Timestamp
}

type AttributeValue struct {
	ID          uuid.UUID
	AttributeID uuid.UUID
	Value       string
	DeletedAt   pgtype.Timestamp
}

type Cart struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	UpdatedAt pgtype.Timestamp
}

type CartItem struct {
	ID               uuid.UUID
	Quantity         int32
	CartID           uuid.UUID
	ProductVariantID uuid.UUID
}

type Category struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type Option struct {
	ID        uuid.UUID
	Name      string
	ProductID uuid.UUID
	DeletedAt pgtype.Timestamp
}

type OptionValue struct {
	ID        uuid.UUID
	Value     string
	DeletedAt pgtype.Timestamp
	OptionID  uuid.UUID
}

type OptionValuesProductVariant struct {
	ProductVariantID uuid.UUID
	OptionValueID    uuid.UUID
}

type Order struct {
	ID          uuid.UUID
	Address     string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	TotalAmount pgtype.Numeric
	IsPaid      bool
	UserID      uuid.UUID
	StatusID    uuid.UUID
	ProviderID  uuid.UUID
}

type OrderItem struct {
	ID               uuid.UUID
	Quantity         int32
	OrderID          uuid.UUID
	Price            pgtype.Numeric
	ProductVariantID uuid.UUID
}

type OrderProvider struct {
	ID   uuid.UUID
	Name string
}

type OrderStatus struct {
	ID   uuid.UUID
	Name string
}

type Product struct {
	ID            uuid.UUID
	Name          string
	Description   string
	Price         pgtype.Numeric
	ViewsCount    int32
	TotalPurchase int32
	Rating        float32
	TrendingScore float32
	CategoryID    uuid.UUID
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	DeletedAt     pgtype.Timestamp
}

type ProductImage struct {
	ID               uuid.UUID
	URL              string
	Order            int32
	CreatedAt        pgtype.Timestamp
	DeletedAt        pgtype.Timestamp
	ProductID        pgtype.UUID
	ProductVariantID pgtype.UUID
}

type ProductVariant struct {
	ID            uuid.UUID
	SKU           string
	Price         pgtype.Numeric
	Quantity      int32
	PurchaseCount int32
	ProductID     uuid.UUID
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	DeletedAt     pgtype.Timestamp
}

type ProductsAttributeValue struct {
	ProductID        uuid.UUID
	AttributeValueID uuid.UUID
}

type Refund struct {
	ID              uuid.UUID
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	StatusID        uuid.UUID
	OrderItemID     uuid.UUID
	ReturnRequestID uuid.UUID
}

type RefundStatus struct {
	ID   uuid.UUID
	Name string
}

type ReturnRequest struct {
	ID          uuid.UUID
	Reason      string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	StatusID    uuid.UUID
	UserID      uuid.UUID
	OrderItemID uuid.UUID
}

type ReturnRequestStatus struct {
	ID   uuid.UUID
	Name string
}

type Review struct {
	ID          uuid.UUID
	Rating      int16
	Content     *string
	ImageURL    string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
	UserID      uuid.UUID
	OrderItemID uuid.UUID
}

type TempAttributeValue struct {
	ID          uuid.UUID
	AttributeID uuid.UUID
	Value       string
	DeletedAt   pgtype.Timestamp
}

type TempCartItem struct {
	ID               uuid.UUID
	Quantity         int32
	CartID           uuid.UUID
	ProductVariantID uuid.UUID
}

type TempOptionValue struct {
	ID        uuid.UUID
	Value     string
	OptionID  uuid.UUID
	DeletedAt pgtype.Timestamp
}

type TempOptionValuesProductVariant struct {
	ProductVariantID uuid.UUID
	OptionValueID    uuid.UUID
}

type TempProductImage struct {
	ID               uuid.UUID
	URL              string
	Order            int32
	ProductID        pgtype.UUID
	ProductVariantID pgtype.UUID
	CreatedAt        pgtype.Timestamp
	DeletedAt        pgtype.Timestamp
}

type TempProductVariant struct {
	ID            uuid.UUID
	SKU           string
	Price         pgtype.Numeric
	Quantity      int32
	PurchaseCount int32
	ProductID     uuid.UUID
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	DeletedAt     pgtype.Timestamp
}

type TempProductsAttributeValue struct {
	ProductID        uuid.UUID
	AttributeValueID uuid.UUID
}

type User struct {
	ID uuid.UUID
}
