// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOrders = `-- name: CountOrders :one
SELECT
  COUNT(*) AS count
FROM
  orders
WHERE
  CASE
    WHEN $1::integer[] IS NULL THEN TRUE
    ELSE id = ANY ($1::integer[])
  END
  AND CASE
    WHEN $2::uuid[] IS NULL THEN TRUE
    ELSE user_id = ANY ($2::uuid[])
  END
  AND CASE
    WHEN $3::integer[] IS NULL THEN TRUE
    ELSE status_id = ANY ($3::integer[])
  END
`

type CountOrdersParams struct {
	IDs       []int32
	UserIds   []uuid.UUID
	StatusIds []int32
}

func (q *Queries) CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders, arg.IDs, arg.UserIds, arg.StatusIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  user_id,
  address,
  total_amount,
  provider_id,
  status_id
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING
  id, address, created_at, updated_at, total_amount, is_paid, user_id, status_id, provider_id
`

type CreateOrderParams struct {
	userID      uuid.UUID
	Address     string
	TotalAmount pgtype.Numeric
	ProviderID  int32
	StatusID    int32
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.userID,
		arg.Address,
		arg.TotalAmount,
		arg.ProviderID,
		arg.StatusID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalAmount,
		&i.IsPaid,
		&i.userID,
		&i.StatusID,
		&i.ProviderID,
	)
	return i, err
}

const createOrderItems = `-- name: CreateOrderItems :many
WITH inserts AS (
  SELECT
    $1 AS quantity,
    $2 AS order_id,
    $3 AS price,
    $4 AS product_variant_id
)
INSERT INTO order_items (
  quantity,
  order_id,
  price,
  product_variant_id
) VALUES (
  inserts.quantity,
  inserts.order_id,
  inserts.price,
  inserts.product_variant_id
)
RETURNING
  id, quantity, order_id, price, product_variant_id
`

type CreateOrderItemsParams struct {
	Quantity         int32
	OrderID          int32
	Price            pgtype.Numeric
	ProductVariantID int32
}

func (q *Queries) CreateOrderItems(ctx context.Context, arg CreateOrderItemsParams) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, createOrderItems,
		arg.Quantity,
		arg.OrderID,
		arg.Price,
		arg.ProductVariantID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.OrderID,
			&i.Price,
			&i.ProductVariantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrder = `-- name: GetOrder :one
SELECT
  id, address, created_at, updated_at, total_amount, is_paid, user_id, status_id, provider_id
FROM
  orders
WHERE
  id = $1
`

type GetOrderParams struct {
	ID int32
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalAmount,
		&i.IsPaid,
		&i.userID,
		&i.StatusID,
		&i.ProviderID,
	)
	return i, err
}

const getOrderItem = `-- name: GetOrderItem :one
SELECT
  id, quantity, order_id, price, product_variant_id
FROM
  order_items
WHERE
  id = $1
`

type GetOrderItemParams struct {
	ID int32
}

func (q *Queries) GetOrderItem(ctx context.Context, arg GetOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, getOrderItem, arg.ID)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.Quantity,
		&i.OrderID,
		&i.Price,
		&i.ProductVariantID,
	)
	return i, err
}

const getOrderProvider = `-- name: GetOrderProvider :one
SELECT
  id, name
FROM
  order_providers
WHERE
  CASE
    WHEN $1::integer IS NULL THEN TRUE
    ELSE id = $1::integer
  END
  AND CASE
    WHEN $2::text IS NULL THEN TRUE
    ELSE name = $2::text
  END
`

type GetOrderProviderParams struct {
	ID   pgtype.Int4
	Name pgtype.Text
}

func (q *Queries) GetOrderProvider(ctx context.Context, arg GetOrderProviderParams) (OrderProvider, error) {
	row := q.db.QueryRow(ctx, getOrderProvider, arg.ID, arg.Name)
	var i OrderProvider
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getOrderStatus = `-- name: GetOrderStatus :one
SELECT
  id, name
FROM
  order_statuses
WHERE
  CASE
    WHEN $1::integer IS NULL THEN TRUE
    ELSE id = $1::integer
  END
  AND CASE
    WHEN $2::text IS NULL THEN TRUE
    ELSE name = $2::text
  END
`

type GetOrderStatusParams struct {
	ID   pgtype.Int4
	Name pgtype.Text
}

func (q *Queries) GetOrderStatus(ctx context.Context, arg GetOrderStatusParams) (OrderStatus, error) {
	row := q.db.QueryRow(ctx, getOrderStatus, arg.ID, arg.Name)
	var i OrderStatus
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT
  id, quantity, order_id, price, product_variant_id
FROM
  order_items
WHERE
  CASE
    WHEN $1::integer[] IS NULL THEN TRUE
    ELSE id = ANY ($1::integer[])
  END
  AND CASE
    WHEN $2::integer[] IS NULL THEN TRUE
    ELSE order_id = ANY ($2::integer[])
  END
ORDER BY
  id
`

type ListOrderItemsParams struct {
	IDs      []int32
	OrderIds []int32
}

func (q *Queries) ListOrderItems(ctx context.Context, arg ListOrderItemsParams) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, arg.IDs, arg.OrderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.OrderID,
			&i.Price,
			&i.ProductVariantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderStatuses = `-- name: ListOrderStatuses :many
SELECT
  id, name
FROM
  order_statuses
WHERE
  CASE
    WHEN $1::integer[] IS NULL THEN TRUE
    ELSE id = ANY ($1::integer[])
  END
ORDER BY
  id ASC
`

type ListOrderStatusesParams struct {
	IDs []int32
}

func (q *Queries) ListOrderStatuses(ctx context.Context, arg ListOrderStatusesParams) ([]OrderStatus, error) {
	rows, err := q.db.Query(ctx, listOrderStatuses, arg.IDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderStatus
	for rows.Next() {
		var i OrderStatus
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT
  id, address, created_at, updated_at, total_amount, is_paid, user_id, status_id, provider_id
FROM
  orders
WHERE
  CASE
    WHEN $1::integer[] IS NULL THEN TRUE
    ELSE id = ANY ($1::integer[])
  END
  AND CASE
    WHEN $2::uuid[] IS NULL THEN TRUE
    ELSE user_id = ANY ($2::uuid[])
  END
  AND CASE
    WHEN $3::integer[] IS NULL THEN TRUE
    ELSE status_id = ANY ($3::integer[])
  END
ORDER BY
  id ASC
OFFSET COALESCE($4::integer, 0)
LIMIT COALESCE($5::integer, 20)
`

type ListOrdersParams struct {
	IDs       []int32
	UserIds   []uuid.UUID
	StatusIds []int32
	Offset    pgtype.Int4
	Limit     pgtype.Int4
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders,
		arg.IDs,
		arg.UserIds,
		arg.StatusIds,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalAmount,
			&i.IsPaid,
			&i.userID,
			&i.StatusID,
			&i.ProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE orders
SET
  user_id = COALESCE($1, user_id),
  status_id = COALESCE($2, status_id),
  updated_at = COALESCE($3::timestamp, NOW())
WHERE
  id = $4
RETURNING
  id, address, created_at, updated_at, total_amount, is_paid, user_id, status_id, provider_id
`

type UpdateOrderParams struct {
	userID    uuid.UUID
	StatusID  int32
	UpdatedAt pgtype.Timestamp
	ID        int32
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrder,
		arg.userID,
		arg.StatusID,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalAmount,
		&i.IsPaid,
		&i.userID,
		&i.StatusID,
		&i.ProviderID,
	)
	return i, err
}
