// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package product

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddImages provides a mock function for the type MockRepository
func (_mock *MockRepository) AddImages(context1 context.Context, imageModels []ImageModel, n int) (*[]ImageModel, error) {
	ret := _mock.Called(context1, imageModels, n)

	if len(ret) == 0 {
		panic("no return value specified for AddImages")
	}

	var r0 *[]ImageModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []ImageModel, int) (*[]ImageModel, error)); ok {
		return returnFunc(context1, imageModels, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []ImageModel, int) *[]ImageModel); ok {
		r0 = returnFunc(context1, imageModels, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]ImageModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []ImageModel, int) error); ok {
		r1 = returnFunc(context1, imageModels, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_AddImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddImages'
type MockRepository_AddImages_Call struct {
	*mock.Call
}

// AddImages is a helper method to define mock.On call
//   - context1 context.Context
//   - imageModels []ImageModel
//   - n int
func (_e *MockRepository_Expecter) AddImages(context1 interface{}, imageModels interface{}, n interface{}) *MockRepository_AddImages_Call {
	return &MockRepository_AddImages_Call{Call: _e.mock.On("AddImages", context1, imageModels, n)}
}

func (_c *MockRepository_AddImages_Call) Run(run func(context1 context.Context, imageModels []ImageModel, n int)) *MockRepository_AddImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []ImageModel
		if args[1] != nil {
			arg1 = args[1].([]ImageModel)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_AddImages_Call) Return(imageModels1 *[]ImageModel, err error) *MockRepository_AddImages_Call {
	_c.Call.Return(imageModels1, err)
	return _c
}

func (_c *MockRepository_AddImages_Call) RunAndReturn(run func(context1 context.Context, imageModels []ImageModel, n int) (*[]ImageModel, error)) *MockRepository_AddImages_Call {
	_c.Call.Return(run)
	return _c
}

// AddOption provides a mock function for the type MockRepository
func (_mock *MockRepository) AddOption(context1 context.Context, optionModel OptionModel, n int) (*OptionModel, error) {
	ret := _mock.Called(context1, optionModel, n)

	if len(ret) == 0 {
		panic("no return value specified for AddOption")
	}

	var r0 *OptionModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, OptionModel, int) (*OptionModel, error)); ok {
		return returnFunc(context1, optionModel, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, OptionModel, int) *OptionModel); ok {
		r0 = returnFunc(context1, optionModel, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*OptionModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, OptionModel, int) error); ok {
		r1 = returnFunc(context1, optionModel, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_AddOption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOption'
type MockRepository_AddOption_Call struct {
	*mock.Call
}

// AddOption is a helper method to define mock.On call
//   - context1 context.Context
//   - optionModel OptionModel
//   - n int
func (_e *MockRepository_Expecter) AddOption(context1 interface{}, optionModel interface{}, n interface{}) *MockRepository_AddOption_Call {
	return &MockRepository_AddOption_Call{Call: _e.mock.On("AddOption", context1, optionModel, n)}
}

func (_c *MockRepository_AddOption_Call) Run(run func(context1 context.Context, optionModel OptionModel, n int)) *MockRepository_AddOption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 OptionModel
		if args[1] != nil {
			arg1 = args[1].(OptionModel)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_AddOption_Call) Return(optionModel1 *OptionModel, err error) *MockRepository_AddOption_Call {
	_c.Call.Return(optionModel1, err)
	return _c
}

func (_c *MockRepository_AddOption_Call) RunAndReturn(run func(context1 context.Context, optionModel OptionModel, n int) (*OptionModel, error)) *MockRepository_AddOption_Call {
	_c.Call.Return(run)
	return _c
}

// AddVariants provides a mock function for the type MockRepository
func (_mock *MockRepository) AddVariants(context1 context.Context, variantModels []VariantModel, n int) (*[]VariantModel, error) {
	ret := _mock.Called(context1, variantModels, n)

	if len(ret) == 0 {
		panic("no return value specified for AddVariants")
	}

	var r0 *[]VariantModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []VariantModel, int) (*[]VariantModel, error)); ok {
		return returnFunc(context1, variantModels, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []VariantModel, int) *[]VariantModel); ok {
		r0 = returnFunc(context1, variantModels, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]VariantModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []VariantModel, int) error); ok {
		r1 = returnFunc(context1, variantModels, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_AddVariants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddVariants'
type MockRepository_AddVariants_Call struct {
	*mock.Call
}

// AddVariants is a helper method to define mock.On call
//   - context1 context.Context
//   - variantModels []VariantModel
//   - n int
func (_e *MockRepository_Expecter) AddVariants(context1 interface{}, variantModels interface{}, n interface{}) *MockRepository_AddVariants_Call {
	return &MockRepository_AddVariants_Call{Call: _e.mock.On("AddVariants", context1, variantModels, n)}
}

func (_c *MockRepository_AddVariants_Call) Run(run func(context1 context.Context, variantModels []VariantModel, n int)) *MockRepository_AddVariants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []VariantModel
		if args[1] != nil {
			arg1 = args[1].([]VariantModel)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_AddVariants_Call) Return(variantModels1 *[]VariantModel, err error) *MockRepository_AddVariants_Call {
	_c.Call.Return(variantModels1, err)
	return _c
}

func (_c *MockRepository_AddVariants_Call) RunAndReturn(run func(context1 context.Context, variantModels []VariantModel, n int) (*[]VariantModel, error)) *MockRepository_AddVariants_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(context1 context.Context, model Model) (*Model, error) {
	ret := _mock.Called(context1, model)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *Model
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Model) (*Model, error)); ok {
		return returnFunc(context1, model)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Model) *Model); ok {
		r0 = returnFunc(context1, model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Model)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Model) error); ok {
		r1 = returnFunc(context1, model)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - model Model
func (_e *MockRepository_Expecter) Create(context1 interface{}, model interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", context1, model)}
}

func (_c *MockRepository_Create_Call) Run(run func(context1 context.Context, model Model)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Model
		if args[1] != nil {
			arg1 = args[1].(Model)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(model1 *Model, err error) *MockRepository_Create_Call {
	_c.Call.Return(model1, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context1 context.Context, model Model) (*Model, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Deletes provides a mock function for the type MockRepository
func (_mock *MockRepository) Deletes(context1 context.Context, ints []int) error {
	ret := _mock.Called(context1, ints)

	if len(ret) == 0 {
		panic("no return value specified for Deletes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) error); ok {
		r0 = returnFunc(context1, ints)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Deletes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deletes'
type MockRepository_Deletes_Call struct {
	*mock.Call
}

// Deletes is a helper method to define mock.On call
//   - context1 context.Context
//   - ints []int
func (_e *MockRepository_Expecter) Deletes(context1 interface{}, ints interface{}) *MockRepository_Deletes_Call {
	return &MockRepository_Deletes_Call{Call: _e.mock.On("Deletes", context1, ints)}
}

func (_c *MockRepository_Deletes_Call) Run(run func(context1 context.Context, ints []int)) *MockRepository_Deletes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Deletes_Call) Return(err error) *MockRepository_Deletes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Deletes_Call) RunAndReturn(run func(context1 context.Context, ints []int) error) *MockRepository_Deletes_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeleteImageURL provides a mock function for the type MockRepository
func (_mock *MockRepository) GetDeleteImageURL(context1 context.Context, n int) (string, error) {
	ret := _mock.Called(context1, n)

	if len(ret) == 0 {
		panic("no return value specified for GetDeleteImageURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (string, error)); ok {
		return returnFunc(context1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) string); ok {
		r0 = returnFunc(context1, n)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(context1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetDeleteImageURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeleteImageURL'
type MockRepository_GetDeleteImageURL_Call struct {
	*mock.Call
}

// GetDeleteImageURL is a helper method to define mock.On call
//   - context1 context.Context
//   - n int
func (_e *MockRepository_Expecter) GetDeleteImageURL(context1 interface{}, n interface{}) *MockRepository_GetDeleteImageURL_Call {
	return &MockRepository_GetDeleteImageURL_Call{Call: _e.mock.On("GetDeleteImageURL", context1, n)}
}

func (_c *MockRepository_GetDeleteImageURL_Call) Run(run func(context1 context.Context, n int)) *MockRepository_GetDeleteImageURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetDeleteImageURL_Call) Return(s string, err error) *MockRepository_GetDeleteImageURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRepository_GetDeleteImageURL_Call) RunAndReturn(run func(context1 context.Context, n int) (string, error)) *MockRepository_GetDeleteImageURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetUploadImageURL provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUploadImageURL(context1 context.Context) (*UploadImageURLModel, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetUploadImageURL")
	}

	var r0 *UploadImageURLModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*UploadImageURLModel, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *UploadImageURLModel); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UploadImageURLModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetUploadImageURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUploadImageURL'
type MockRepository_GetUploadImageURL_Call struct {
	*mock.Call
}

// GetUploadImageURL is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockRepository_Expecter) GetUploadImageURL(context1 interface{}) *MockRepository_GetUploadImageURL_Call {
	return &MockRepository_GetUploadImageURL_Call{Call: _e.mock.On("GetUploadImageURL", context1)}
}

func (_c *MockRepository_GetUploadImageURL_Call) Run(run func(context1 context.Context)) *MockRepository_GetUploadImageURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetUploadImageURL_Call) Return(uploadImageURLModel *UploadImageURLModel, err error) *MockRepository_GetUploadImageURL_Call {
	_c.Call.Return(uploadImageURLModel, err)
	return _c
}

func (_c *MockRepository_GetUploadImageURL_Call) RunAndReturn(run func(context1 context.Context) (*UploadImageURLModel, error)) *MockRepository_GetUploadImageURL_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRepository
func (_mock *MockRepository) List(context1 context.Context, queryParams QueryParams) (*PaginationModel, error) {
	ret := _mock.Called(context1, queryParams)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *PaginationModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, QueryParams) (*PaginationModel, error)); ok {
		return returnFunc(context1, queryParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, QueryParams) *PaginationModel); ok {
		r0 = returnFunc(context1, queryParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PaginationModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, QueryParams) error); ok {
		r1 = returnFunc(context1, queryParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - queryParams QueryParams
func (_e *MockRepository_Expecter) List(context1 interface{}, queryParams interface{}) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", context1, queryParams)}
}

func (_c *MockRepository_List_Call) Run(run func(context1 context.Context, queryParams QueryParams)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 QueryParams
		if args[1] != nil {
			arg1 = args[1].(QueryParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(paginationModel *PaginationModel, err error) *MockRepository_List_Call {
	_c.Call.Return(paginationModel, err)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(context1 context.Context, queryParams QueryParams) (*PaginationModel, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// MoveImage provides a mock function for the type MockRepository
func (_mock *MockRepository) MoveImage(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for MoveImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MoveImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MoveImage'
type MockRepository_MoveImage_Call struct {
	*mock.Call
}

// MoveImage is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockRepository_Expecter) MoveImage(context1 interface{}, s interface{}) *MockRepository_MoveImage_Call {
	return &MockRepository_MoveImage_Call{Call: _e.mock.On("MoveImage", context1, s)}
}

func (_c *MockRepository_MoveImage_Call) Run(run func(context1 context.Context, s string)) *MockRepository_MoveImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_MoveImage_Call) Return(err error) *MockRepository_MoveImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MoveImage_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockRepository_MoveImage_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepository
func (_mock *MockRepository) Update(context1 context.Context, model Model, n int) (*Model, error) {
	ret := _mock.Called(context1, model, n)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *Model
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Model, int) (*Model, error)); ok {
		return returnFunc(context1, model, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Model, int) *Model); ok {
		r0 = returnFunc(context1, model, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Model)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Model, int) error); ok {
		r1 = returnFunc(context1, model, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - model Model
//   - n int
func (_e *MockRepository_Expecter) Update(context1 interface{}, model interface{}, n interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", context1, model, n)}
}

func (_c *MockRepository_Update_Call) Run(run func(context1 context.Context, model Model, n int)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Model
		if args[1] != nil {
			arg1 = args[1].(Model)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(model1 *Model, err error) *MockRepository_Update_Call {
	_c.Call.Return(model1, err)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(context1 context.Context, model Model, n int) (*Model, error)) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOption provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateOption(context1 context.Context, optionModel OptionModel, n int) (*OptionModel, error) {
	ret := _mock.Called(context1, optionModel, n)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOption")
	}

	var r0 *OptionModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, OptionModel, int) (*OptionModel, error)); ok {
		return returnFunc(context1, optionModel, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, OptionModel, int) *OptionModel); ok {
		r0 = returnFunc(context1, optionModel, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*OptionModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, OptionModel, int) error); ok {
		r1 = returnFunc(context1, optionModel, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_UpdateOption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOption'
type MockRepository_UpdateOption_Call struct {
	*mock.Call
}

// UpdateOption is a helper method to define mock.On call
//   - context1 context.Context
//   - optionModel OptionModel
//   - n int
func (_e *MockRepository_Expecter) UpdateOption(context1 interface{}, optionModel interface{}, n interface{}) *MockRepository_UpdateOption_Call {
	return &MockRepository_UpdateOption_Call{Call: _e.mock.On("UpdateOption", context1, optionModel, n)}
}

func (_c *MockRepository_UpdateOption_Call) Run(run func(context1 context.Context, optionModel OptionModel, n int)) *MockRepository_UpdateOption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 OptionModel
		if args[1] != nil {
			arg1 = args[1].(OptionModel)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateOption_Call) Return(optionModel1 *OptionModel, err error) *MockRepository_UpdateOption_Call {
	_c.Call.Return(optionModel1, err)
	return _c
}

func (_c *MockRepository_UpdateOption_Call) RunAndReturn(run func(context1 context.Context, optionModel OptionModel, n int) (*OptionModel, error)) *MockRepository_UpdateOption_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateVariants provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateVariants(context1 context.Context, variantModels []VariantModel, n int) (*[]VariantModel, error) {
	ret := _mock.Called(context1, variantModels, n)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVariants")
	}

	var r0 *[]VariantModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []VariantModel, int) (*[]VariantModel, error)); ok {
		return returnFunc(context1, variantModels, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []VariantModel, int) *[]VariantModel); ok {
		r0 = returnFunc(context1, variantModels, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]VariantModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []VariantModel, int) error); ok {
		r1 = returnFunc(context1, variantModels, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_UpdateVariants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateVariants'
type MockRepository_UpdateVariants_Call struct {
	*mock.Call
}

// UpdateVariants is a helper method to define mock.On call
//   - context1 context.Context
//   - variantModels []VariantModel
//   - n int
func (_e *MockRepository_Expecter) UpdateVariants(context1 interface{}, variantModels interface{}, n interface{}) *MockRepository_UpdateVariants_Call {
	return &MockRepository_UpdateVariants_Call{Call: _e.mock.On("UpdateVariants", context1, variantModels, n)}
}

func (_c *MockRepository_UpdateVariants_Call) Run(run func(context1 context.Context, variantModels []VariantModel, n int)) *MockRepository_UpdateVariants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []VariantModel
		if args[1] != nil {
			arg1 = args[1].([]VariantModel)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateVariants_Call) Return(variantModels1 *[]VariantModel, err error) *MockRepository_UpdateVariants_Call {
	_c.Call.Return(variantModels1, err)
	return _c
}

func (_c *MockRepository_UpdateVariants_Call) RunAndReturn(run func(context1 context.Context, variantModels []VariantModel, n int) (*[]VariantModel, error)) *MockRepository_UpdateVariants_Call {
	_c.Call.Return(run)
	return _c
}
