// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cart

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddItem provides a mock function for the type MockRepository
func (_mock *MockRepository) AddItem(context1 context.Context, itemModel *ItemModel) (*ItemModel, error) {
	ret := _mock.Called(context1, itemModel)

	if len(ret) == 0 {
		panic("no return value specified for AddItem")
	}

	var r0 *ItemModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ItemModel) (*ItemModel, error)); ok {
		return returnFunc(context1, itemModel)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ItemModel) *ItemModel); ok {
		r0 = returnFunc(context1, itemModel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ItemModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ItemModel) error); ok {
		r1 = returnFunc(context1, itemModel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_AddItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddItem'
type MockRepository_AddItem_Call struct {
	*mock.Call
}

// AddItem is a helper method to define mock.On call
//   - context1 context.Context
//   - itemModel *ItemModel
func (_e *MockRepository_Expecter) AddItem(context1 interface{}, itemModel interface{}) *MockRepository_AddItem_Call {
	return &MockRepository_AddItem_Call{Call: _e.mock.On("AddItem", context1, itemModel)}
}

func (_c *MockRepository_AddItem_Call) Run(run func(context1 context.Context, itemModel *ItemModel)) *MockRepository_AddItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ItemModel
		if args[1] != nil {
			arg1 = args[1].(*ItemModel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_AddItem_Call) Return(itemModel1 *ItemModel, err error) *MockRepository_AddItem_Call {
	_c.Call.Return(itemModel1, err)
	return _c
}

func (_c *MockRepository_AddItem_Call) RunAndReturn(run func(context1 context.Context, itemModel *ItemModel) (*ItemModel, error)) *MockRepository_AddItem_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockRepository
func (_mock *MockRepository) Get(context1 context.Context, n int, queryParams *QueryParams) (*Model, error) {
	ret := _mock.Called(context1, n, queryParams)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *Model
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *QueryParams) (*Model, error)); ok {
		return returnFunc(context1, n, queryParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *QueryParams) *Model); ok {
		r0 = returnFunc(context1, n, queryParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Model)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, *QueryParams) error); ok {
		r1 = returnFunc(context1, n, queryParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - n int
//   - queryParams *QueryParams
func (_e *MockRepository_Expecter) Get(context1 interface{}, n interface{}, queryParams interface{}) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", context1, n, queryParams)}
}

func (_c *MockRepository_Get_Call) Run(run func(context1 context.Context, n int, queryParams *QueryParams)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *QueryParams
		if args[2] != nil {
			arg2 = args[2].(*QueryParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(model *Model, err error) *MockRepository_Get_Call {
	_c.Call.Return(model, err)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(context1 context.Context, n int, queryParams *QueryParams) (*Model, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveItem provides a mock function for the type MockRepository
func (_mock *MockRepository) RemoveItem(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for RemoveItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RemoveItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveItem'
type MockRepository_RemoveItem_Call struct {
	*mock.Call
}

// RemoveItem is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockRepository_Expecter) RemoveItem(context1 interface{}, s interface{}) *MockRepository_RemoveItem_Call {
	return &MockRepository_RemoveItem_Call{Call: _e.mock.On("RemoveItem", context1, s)}
}

func (_c *MockRepository_RemoveItem_Call) Run(run func(context1 context.Context, s string)) *MockRepository_RemoveItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_RemoveItem_Call) Return(err error) *MockRepository_RemoveItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RemoveItem_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockRepository_RemoveItem_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateItem(context1 context.Context, itemModel *ItemModel, s string) (*ItemModel, error) {
	ret := _mock.Called(context1, itemModel, s)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 *ItemModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ItemModel, string) (*ItemModel, error)); ok {
		return returnFunc(context1, itemModel, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ItemModel, string) *ItemModel); ok {
		r0 = returnFunc(context1, itemModel, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ItemModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ItemModel, string) error); ok {
		r1 = returnFunc(context1, itemModel, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type MockRepository_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - context1 context.Context
//   - itemModel *ItemModel
//   - s string
func (_e *MockRepository_Expecter) UpdateItem(context1 interface{}, itemModel interface{}, s interface{}) *MockRepository_UpdateItem_Call {
	return &MockRepository_UpdateItem_Call{Call: _e.mock.On("UpdateItem", context1, itemModel, s)}
}

func (_c *MockRepository_UpdateItem_Call) Run(run func(context1 context.Context, itemModel *ItemModel, s string)) *MockRepository_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ItemModel
		if args[1] != nil {
			arg1 = args[1].(*ItemModel)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateItem_Call) Return(itemModel1 *ItemModel, err error) *MockRepository_UpdateItem_Call {
	_c.Call.Return(itemModel1, err)
	return _c
}

func (_c *MockRepository_UpdateItem_Call) RunAndReturn(run func(context1 context.Context, itemModel *ItemModel, s string) (*ItemModel, error)) *MockRepository_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}
