// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"backend/internal/domain"

	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAttribute creates a new instance of MockAttribute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttribute(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttribute {
	mock := &MockAttribute{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAttribute is an autogenerated mock type for the Attribute type
type MockAttribute struct {
	mock.Mock
}

type MockAttribute_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttribute) EXPECT() *MockAttribute_Expecter {
	return &MockAttribute_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockAttribute
func (_mock *MockAttribute) Count(tx pgx.Tx, ids *[]int, deleted string, limit int, offset int) (*int, error) {
	ret := _mock.Called(tx, ids, deleted, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 *int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, *[]int, string, int, int) (*int, error)); ok {
		return returnFunc(tx, ids, deleted, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, *[]int, string, int, int) *int); ok {
		r0 = returnFunc(tx, ids, deleted, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, *[]int, string, int, int) error); ok {
		r1 = returnFunc(tx, ids, deleted, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttribute_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockAttribute_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - tx pgx.Tx
//   - ids *[]int
//   - deleted string
//   - limit int
//   - offset int
func (_e *MockAttribute_Expecter) Count(tx interface{}, ids interface{}, deleted interface{}, limit interface{}, offset interface{}) *MockAttribute_Count_Call {
	return &MockAttribute_Count_Call{Call: _e.mock.On("Count", tx, ids, deleted, limit, offset)}
}

func (_c *MockAttribute_Count_Call) Run(run func(tx pgx.Tx, ids *[]int, deleted string, limit int, offset int)) *MockAttribute_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 *[]int
		if args[1] != nil {
			arg1 = args[1].(*[]int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAttribute_Count_Call) Return(n *int, err error) *MockAttribute_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAttribute_Count_Call) RunAndReturn(run func(tx pgx.Tx, ids *[]int, deleted string, limit int, offset int) (*int, error)) *MockAttribute_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockAttribute
func (_mock *MockAttribute) Create(tx pgx.Tx, code string, name string) (*domain.Attribute, error) {
	ret := _mock.Called(tx, code, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Attribute
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, string, string) (*domain.Attribute, error)); ok {
		return returnFunc(tx, code, name)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, string, string) *domain.Attribute); ok {
		r0 = returnFunc(tx, code, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Attribute)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, string, string) error); ok {
		r1 = returnFunc(tx, code, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttribute_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAttribute_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - tx pgx.Tx
//   - code string
//   - name string
func (_e *MockAttribute_Expecter) Create(tx interface{}, code interface{}, name interface{}) *MockAttribute_Create_Call {
	return &MockAttribute_Create_Call{Call: _e.mock.On("Create", tx, code, name)}
}

func (_c *MockAttribute_Create_Call) Run(run func(tx pgx.Tx, code string, name string)) *MockAttribute_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAttribute_Create_Call) Return(attribute *domain.Attribute, err error) *MockAttribute_Create_Call {
	_c.Call.Return(attribute, err)
	return _c
}

func (_c *MockAttribute_Create_Call) RunAndReturn(run func(tx pgx.Tx, code string, name string) (*domain.Attribute, error)) *MockAttribute_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateValues provides a mock function for the type MockAttribute
func (_mock *MockAttribute) CreateValues(tx pgx.Tx, attributeID int, values []string) (*[]domain.AttributeValue, error) {
	ret := _mock.Called(tx, attributeID, values)

	if len(ret) == 0 {
		panic("no return value specified for CreateValues")
	}

	var r0 *[]domain.AttributeValue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, []string) (*[]domain.AttributeValue, error)); ok {
		return returnFunc(tx, attributeID, values)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, []string) *[]domain.AttributeValue); ok {
		r0 = returnFunc(tx, attributeID, values)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.AttributeValue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, int, []string) error); ok {
		r1 = returnFunc(tx, attributeID, values)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttribute_CreateValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateValues'
type MockAttribute_CreateValues_Call struct {
	*mock.Call
}

// CreateValues is a helper method to define mock.On call
//   - tx pgx.Tx
//   - attributeID int
//   - values []string
func (_e *MockAttribute_Expecter) CreateValues(tx interface{}, attributeID interface{}, values interface{}) *MockAttribute_CreateValues_Call {
	return &MockAttribute_CreateValues_Call{Call: _e.mock.On("CreateValues", tx, attributeID, values)}
}

func (_c *MockAttribute_CreateValues_Call) Run(run func(tx pgx.Tx, attributeID int, values []string)) *MockAttribute_CreateValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAttribute_CreateValues_Call) Return(attributeValues *[]domain.AttributeValue, err error) *MockAttribute_CreateValues_Call {
	_c.Call.Return(attributeValues, err)
	return _c
}

func (_c *MockAttribute_CreateValues_Call) RunAndReturn(run func(tx pgx.Tx, attributeID int, values []string) (*[]domain.AttributeValue, error)) *MockAttribute_CreateValues_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockAttribute
func (_mock *MockAttribute) Delete(tx pgx.Tx, id int) error {
	ret := _mock.Called(tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int) error); ok {
		r0 = returnFunc(tx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAttribute_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAttribute_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - tx pgx.Tx
//   - id int
func (_e *MockAttribute_Expecter) Delete(tx interface{}, id interface{}) *MockAttribute_Delete_Call {
	return &MockAttribute_Delete_Call{Call: _e.mock.On("Delete", tx, id)}
}

func (_c *MockAttribute_Delete_Call) Run(run func(tx pgx.Tx, id int)) *MockAttribute_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttribute_Delete_Call) Return(err error) *MockAttribute_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAttribute_Delete_Call) RunAndReturn(run func(tx pgx.Tx, id int) error) *MockAttribute_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteValue provides a mock function for the type MockAttribute
func (_mock *MockAttribute) DeleteValue(tx pgx.Tx, attributeValueID int) error {
	ret := _mock.Called(tx, attributeValueID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteValue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int) error); ok {
		r0 = returnFunc(tx, attributeValueID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAttribute_DeleteValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteValue'
type MockAttribute_DeleteValue_Call struct {
	*mock.Call
}

// DeleteValue is a helper method to define mock.On call
//   - tx pgx.Tx
//   - attributeValueID int
func (_e *MockAttribute_Expecter) DeleteValue(tx interface{}, attributeValueID interface{}) *MockAttribute_DeleteValue_Call {
	return &MockAttribute_DeleteValue_Call{Call: _e.mock.On("DeleteValue", tx, attributeValueID)}
}

func (_c *MockAttribute_DeleteValue_Call) Run(run func(tx pgx.Tx, attributeValueID int)) *MockAttribute_DeleteValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttribute_DeleteValue_Call) Return(err error) *MockAttribute_DeleteValue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAttribute_DeleteValue_Call) RunAndReturn(run func(tx pgx.Tx, attributeValueID int) error) *MockAttribute_DeleteValue_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockAttribute
func (_mock *MockAttribute) Get(tx pgx.Tx, id int) (*domain.Attribute, error) {
	ret := _mock.Called(tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Attribute
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int) (*domain.Attribute, error)); ok {
		return returnFunc(tx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int) *domain.Attribute); ok {
		r0 = returnFunc(tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Attribute)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, int) error); ok {
		r1 = returnFunc(tx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttribute_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAttribute_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - tx pgx.Tx
//   - id int
func (_e *MockAttribute_Expecter) Get(tx interface{}, id interface{}) *MockAttribute_Get_Call {
	return &MockAttribute_Get_Call{Call: _e.mock.On("Get", tx, id)}
}

func (_c *MockAttribute_Get_Call) Run(run func(tx pgx.Tx, id int)) *MockAttribute_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttribute_Get_Call) Return(attribute *domain.Attribute, err error) *MockAttribute_Get_Call {
	_c.Call.Return(attribute, err)
	return _c
}

func (_c *MockAttribute_Get_Call) RunAndReturn(run func(tx pgx.Tx, id int) (*domain.Attribute, error)) *MockAttribute_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockAttribute
func (_mock *MockAttribute) List(tx pgx.Tx, ids *[]int, search *string, deleted string, limit int, offset int) (*[]domain.Attribute, error) {
	ret := _mock.Called(tx, ids, search, deleted, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *[]domain.Attribute
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, *[]int, *string, string, int, int) (*[]domain.Attribute, error)); ok {
		return returnFunc(tx, ids, search, deleted, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, *[]int, *string, string, int, int) *[]domain.Attribute); ok {
		r0 = returnFunc(tx, ids, search, deleted, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.Attribute)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, *[]int, *string, string, int, int) error); ok {
		r1 = returnFunc(tx, ids, search, deleted, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttribute_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAttribute_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - tx pgx.Tx
//   - ids *[]int
//   - search *string
//   - deleted string
//   - limit int
//   - offset int
func (_e *MockAttribute_Expecter) List(tx interface{}, ids interface{}, search interface{}, deleted interface{}, limit interface{}, offset interface{}) *MockAttribute_List_Call {
	return &MockAttribute_List_Call{Call: _e.mock.On("List", tx, ids, search, deleted, limit, offset)}
}

func (_c *MockAttribute_List_Call) Run(run func(tx pgx.Tx, ids *[]int, search *string, deleted string, limit int, offset int)) *MockAttribute_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 *[]int
		if args[1] != nil {
			arg1 = args[1].(*[]int)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockAttribute_List_Call) Return(attributes *[]domain.Attribute, err error) *MockAttribute_List_Call {
	_c.Call.Return(attributes, err)
	return _c
}

func (_c *MockAttribute_List_Call) RunAndReturn(run func(tx pgx.Tx, ids *[]int, search *string, deleted string, limit int, offset int) (*[]domain.Attribute, error)) *MockAttribute_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockAttribute
func (_mock *MockAttribute) Update(tx pgx.Tx, id int, code *string, name *string) (*domain.Attribute, error) {
	ret := _mock.Called(tx, id, code, name)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Attribute
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, *string, *string) (*domain.Attribute, error)); ok {
		return returnFunc(tx, id, code, name)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, *string, *string) *domain.Attribute); ok {
		r0 = returnFunc(tx, id, code, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Attribute)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, int, *string, *string) error); ok {
		r1 = returnFunc(tx, id, code, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttribute_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAttribute_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - tx pgx.Tx
//   - id int
//   - code *string
//   - name *string
func (_e *MockAttribute_Expecter) Update(tx interface{}, id interface{}, code interface{}, name interface{}) *MockAttribute_Update_Call {
	return &MockAttribute_Update_Call{Call: _e.mock.On("Update", tx, id, code, name)}
}

func (_c *MockAttribute_Update_Call) Run(run func(tx pgx.Tx, id int, code *string, name *string)) *MockAttribute_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAttribute_Update_Call) Return(attribute *domain.Attribute, err error) *MockAttribute_Update_Call {
	_c.Call.Return(attribute, err)
	return _c
}

func (_c *MockAttribute_Update_Call) RunAndReturn(run func(tx pgx.Tx, id int, code *string, name *string) (*domain.Attribute, error)) *MockAttribute_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateValue provides a mock function for the type MockAttribute
func (_mock *MockAttribute) UpdateValue(tx pgx.Tx, attributeValueID int, value *string) (*domain.AttributeValue, error) {
	ret := _mock.Called(tx, attributeValueID, value)

	if len(ret) == 0 {
		panic("no return value specified for UpdateValue")
	}

	var r0 *domain.AttributeValue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, *string) (*domain.AttributeValue, error)); ok {
		return returnFunc(tx, attributeValueID, value)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, *string) *domain.AttributeValue); ok {
		r0 = returnFunc(tx, attributeValueID, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AttributeValue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, int, *string) error); ok {
		r1 = returnFunc(tx, attributeValueID, value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttribute_UpdateValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateValue'
type MockAttribute_UpdateValue_Call struct {
	*mock.Call
}

// UpdateValue is a helper method to define mock.On call
//   - tx pgx.Tx
//   - attributeValueID int
//   - value *string
func (_e *MockAttribute_Expecter) UpdateValue(tx interface{}, attributeValueID interface{}, value interface{}) *MockAttribute_UpdateValue_Call {
	return &MockAttribute_UpdateValue_Call{Call: _e.mock.On("UpdateValue", tx, attributeValueID, value)}
}

func (_c *MockAttribute_UpdateValue_Call) Run(run func(tx pgx.Tx, attributeValueID int, value *string)) *MockAttribute_UpdateValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAttribute_UpdateValue_Call) Return(attributeValue *domain.AttributeValue, err error) *MockAttribute_UpdateValue_Call {
	_c.Call.Return(attributeValue, err)
	return _c
}

func (_c *MockAttribute_UpdateValue_Call) RunAndReturn(run func(tx pgx.Tx, attributeValueID int, value *string) (*domain.AttributeValue, error)) *MockAttribute_UpdateValue_Call {
	_c.Call.Return(run)
	return _c
}
