// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"backend/internal/domain"

	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCategory creates a new instance of MockCategory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategory {
	mock := &MockCategory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCategory is an autogenerated mock type for the Category type
type MockCategory struct {
	mock.Mock
}

type MockCategory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategory) EXPECT() *MockCategory_Expecter {
	return &MockCategory_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockCategory
func (_mock *MockCategory) Count(tx pgx.Tx, limit int, offset int) (*int, error) {
	ret := _mock.Called(tx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 *int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, int) (*int, error)); ok {
		return returnFunc(tx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, int) *int); ok {
		r0 = returnFunc(tx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, int, int) error); ok {
		r1 = returnFunc(tx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategory_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockCategory_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - tx pgx.Tx
//   - limit int
//   - offset int
func (_e *MockCategory_Expecter) Count(tx interface{}, limit interface{}, offset interface{}) *MockCategory_Count_Call {
	return &MockCategory_Count_Call{Call: _e.mock.On("Count", tx, limit, offset)}
}

func (_c *MockCategory_Count_Call) Run(run func(tx pgx.Tx, limit int, offset int)) *MockCategory_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCategory_Count_Call) Return(n *int, err error) *MockCategory_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCategory_Count_Call) RunAndReturn(run func(tx pgx.Tx, limit int, offset int) (*int, error)) *MockCategory_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockCategory
func (_mock *MockCategory) Create(tx pgx.Tx, name string) (*domain.Category, error) {
	ret := _mock.Called(tx, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, string) (*domain.Category, error)); ok {
		return returnFunc(tx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, string) *domain.Category); ok {
		r0 = returnFunc(tx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, string) error); ok {
		r1 = returnFunc(tx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategory_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCategory_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - tx pgx.Tx
//   - name string
func (_e *MockCategory_Expecter) Create(tx interface{}, name interface{}) *MockCategory_Create_Call {
	return &MockCategory_Create_Call{Call: _e.mock.On("Create", tx, name)}
}

func (_c *MockCategory_Create_Call) Run(run func(tx pgx.Tx, name string)) *MockCategory_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategory_Create_Call) Return(category *domain.Category, err error) *MockCategory_Create_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *MockCategory_Create_Call) RunAndReturn(run func(tx pgx.Tx, name string) (*domain.Category, error)) *MockCategory_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCategory
func (_mock *MockCategory) Delete(tx pgx.Tx, id int) error {
	ret := _mock.Called(tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int) error); ok {
		r0 = returnFunc(tx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCategory_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCategory_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - tx pgx.Tx
//   - id int
func (_e *MockCategory_Expecter) Delete(tx interface{}, id interface{}) *MockCategory_Delete_Call {
	return &MockCategory_Delete_Call{Call: _e.mock.On("Delete", tx, id)}
}

func (_c *MockCategory_Delete_Call) Run(run func(tx pgx.Tx, id int)) *MockCategory_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategory_Delete_Call) Return(err error) *MockCategory_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCategory_Delete_Call) RunAndReturn(run func(tx pgx.Tx, id int) error) *MockCategory_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockCategory
func (_mock *MockCategory) Get(tx pgx.Tx, id int) (*domain.Category, error) {
	ret := _mock.Called(tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int) (*domain.Category, error)); ok {
		return returnFunc(tx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int) *domain.Category); ok {
		r0 = returnFunc(tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, int) error); ok {
		r1 = returnFunc(tx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategory_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCategory_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - tx pgx.Tx
//   - id int
func (_e *MockCategory_Expecter) Get(tx interface{}, id interface{}) *MockCategory_Get_Call {
	return &MockCategory_Get_Call{Call: _e.mock.On("Get", tx, id)}
}

func (_c *MockCategory_Get_Call) Run(run func(tx pgx.Tx, id int)) *MockCategory_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategory_Get_Call) Return(category *domain.Category, err error) *MockCategory_Get_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *MockCategory_Get_Call) RunAndReturn(run func(tx pgx.Tx, id int) (*domain.Category, error)) *MockCategory_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockCategory
func (_mock *MockCategory) List(tx pgx.Tx, search *string, limit int, offset int) (*[]domain.Category, error) {
	ret := _mock.Called(tx, search, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *[]domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, *string, int, int) (*[]domain.Category, error)); ok {
		return returnFunc(tx, search, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, *string, int, int) *[]domain.Category); ok {
		r0 = returnFunc(tx, search, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, *string, int, int) error); ok {
		r1 = returnFunc(tx, search, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategory_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCategory_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - tx pgx.Tx
//   - search *string
//   - limit int
//   - offset int
func (_e *MockCategory_Expecter) List(tx interface{}, search interface{}, limit interface{}, offset interface{}) *MockCategory_List_Call {
	return &MockCategory_List_Call{Call: _e.mock.On("List", tx, search, limit, offset)}
}

func (_c *MockCategory_List_Call) Run(run func(tx pgx.Tx, search *string, limit int, offset int)) *MockCategory_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCategory_List_Call) Return(categorys *[]domain.Category, err error) *MockCategory_List_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *MockCategory_List_Call) RunAndReturn(run func(tx pgx.Tx, search *string, limit int, offset int) (*[]domain.Category, error)) *MockCategory_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockCategory
func (_mock *MockCategory) Update(tx pgx.Tx, id int, name *string) (*domain.Category, error) {
	ret := _mock.Called(tx, id, name)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, *string) (*domain.Category, error)); ok {
		return returnFunc(tx, id, name)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, *string) *domain.Category); ok {
		r0 = returnFunc(tx, id, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, int, *string) error); ok {
		r1 = returnFunc(tx, id, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategory_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCategory_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - tx pgx.Tx
//   - id int
//   - name *string
func (_e *MockCategory_Expecter) Update(tx interface{}, id interface{}, name interface{}) *MockCategory_Update_Call {
	return &MockCategory_Update_Call{Call: _e.mock.On("Update", tx, id, name)}
}

func (_c *MockCategory_Update_Call) Run(run func(tx pgx.Tx, id int, name *string)) *MockCategory_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCategory_Update_Call) Return(category *domain.Category, err error) *MockCategory_Update_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *MockCategory_Update_Call) RunAndReturn(run func(tx pgx.Tx, id int, name *string) (*domain.Category, error)) *MockCategory_Update_Call {
	_c.Call.Return(run)
	return _c
}
