// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"backend/internal/domain"

	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProduct creates a new instance of MockProduct. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProduct(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProduct {
	mock := &MockProduct{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProduct is an autogenerated mock type for the Product type
type MockProduct struct {
	mock.Mock
}

type MockProduct_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProduct) EXPECT() *MockProduct_Expecter {
	return &MockProduct_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockProduct
func (_mock *MockProduct) Count(tx pgx.Tx, ids *[]int, min_price *int64, max_price *int64, rating *float64, category_ids *[]int, deleted string, sort_rating *string, sort_price *string, limit int, offset int) (*int, error) {
	ret := _mock.Called(tx, ids, min_price, max_price, rating, category_ids, deleted, sort_rating, sort_price, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 *int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, *[]int, *int64, *int64, *float64, *[]int, string, *string, *string, int, int) (*int, error)); ok {
		return returnFunc(tx, ids, min_price, max_price, rating, category_ids, deleted, sort_rating, sort_price, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, *[]int, *int64, *int64, *float64, *[]int, string, *string, *string, int, int) *int); ok {
		r0 = returnFunc(tx, ids, min_price, max_price, rating, category_ids, deleted, sort_rating, sort_price, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, *[]int, *int64, *int64, *float64, *[]int, string, *string, *string, int, int) error); ok {
		r1 = returnFunc(tx, ids, min_price, max_price, rating, category_ids, deleted, sort_rating, sort_price, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProduct_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockProduct_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - tx pgx.Tx
//   - ids *[]int
//   - min_price *int64
//   - max_price *int64
//   - rating *float64
//   - category_ids *[]int
//   - deleted string
//   - sort_rating *string
//   - sort_price *string
//   - limit int
//   - offset int
func (_e *MockProduct_Expecter) Count(tx interface{}, ids interface{}, min_price interface{}, max_price interface{}, rating interface{}, category_ids interface{}, deleted interface{}, sort_rating interface{}, sort_price interface{}, limit interface{}, offset interface{}) *MockProduct_Count_Call {
	return &MockProduct_Count_Call{Call: _e.mock.On("Count", tx, ids, min_price, max_price, rating, category_ids, deleted, sort_rating, sort_price, limit, offset)}
}

func (_c *MockProduct_Count_Call) Run(run func(tx pgx.Tx, ids *[]int, min_price *int64, max_price *int64, rating *float64, category_ids *[]int, deleted string, sort_rating *string, sort_price *string, limit int, offset int)) *MockProduct_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 *[]int
		if args[1] != nil {
			arg1 = args[1].(*[]int)
		}
		var arg2 *int64
		if args[2] != nil {
			arg2 = args[2].(*int64)
		}
		var arg3 *int64
		if args[3] != nil {
			arg3 = args[3].(*int64)
		}
		var arg4 *float64
		if args[4] != nil {
			arg4 = args[4].(*float64)
		}
		var arg5 *[]int
		if args[5] != nil {
			arg5 = args[5].(*[]int)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		var arg7 *string
		if args[7] != nil {
			arg7 = args[7].(*string)
		}
		var arg8 *string
		if args[8] != nil {
			arg8 = args[8].(*string)
		}
		var arg9 int
		if args[9] != nil {
			arg9 = args[9].(int)
		}
		var arg10 int
		if args[10] != nil {
			arg10 = args[10].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
			arg8,
			arg9,
			arg10,
		)
	})
	return _c
}

func (_c *MockProduct_Count_Call) Return(n *int, err error) *MockProduct_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockProduct_Count_Call) RunAndReturn(run func(tx pgx.Tx, ids *[]int, min_price *int64, max_price *int64, rating *float64, category_ids *[]int, deleted string, sort_rating *string, sort_price *string, limit int, offset int) (*int, error)) *MockProduct_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockProduct
func (_mock *MockProduct) Create(tx pgx.Tx, name string, description string, attributeValueIDs []int, categoryID int) (*domain.Product, error) {
	ret := _mock.Called(tx, name, description, attributeValueIDs, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, string, string, []int, int) (*domain.Product, error)); ok {
		return returnFunc(tx, name, description, attributeValueIDs, categoryID)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, string, string, []int, int) *domain.Product); ok {
		r0 = returnFunc(tx, name, description, attributeValueIDs, categoryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, string, string, []int, int) error); ok {
		r1 = returnFunc(tx, name, description, attributeValueIDs, categoryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProduct_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProduct_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - tx pgx.Tx
//   - name string
//   - description string
//   - attributeValueIDs []int
//   - categoryID int
func (_e *MockProduct_Expecter) Create(tx interface{}, name interface{}, description interface{}, attributeValueIDs interface{}, categoryID interface{}) *MockProduct_Create_Call {
	return &MockProduct_Create_Call{Call: _e.mock.On("Create", tx, name, description, attributeValueIDs, categoryID)}
}

func (_c *MockProduct_Create_Call) Run(run func(tx pgx.Tx, name string, description string, attributeValueIDs []int, categoryID int)) *MockProduct_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []int
		if args[3] != nil {
			arg3 = args[3].([]int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockProduct_Create_Call) Return(product *domain.Product, err error) *MockProduct_Create_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockProduct_Create_Call) RunAndReturn(run func(tx pgx.Tx, name string, description string, attributeValueIDs []int, categoryID int) (*domain.Product, error)) *MockProduct_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateImages provides a mock function for the type MockProduct
func (_mock *MockProduct) CreateImages(tx pgx.Tx, productID int, images []struct {
	url   string
	order int
}) (*[]domain.ProductImage, error) {
	ret := _mock.Called(tx, productID, images)

	if len(ret) == 0 {
		panic("no return value specified for CreateImages")
	}

	var r0 *[]domain.ProductImage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, []struct {
		url   string
		order int
	}) (*[]domain.ProductImage, error)); ok {
		return returnFunc(tx, productID, images)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, []struct {
		url   string
		order int
	}) *[]domain.ProductImage); ok {
		r0 = returnFunc(tx, productID, images)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.ProductImage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, int, []struct {
		url   string
		order int
	}) error); ok {
		r1 = returnFunc(tx, productID, images)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProduct_CreateImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateImages'
type MockProduct_CreateImages_Call struct {
	*mock.Call
}

// CreateImages is a helper method to define mock.On call
//   - tx pgx.Tx
//   - productID int
//   - images []struct{url string; order int}
func (_e *MockProduct_Expecter) CreateImages(tx interface{}, productID interface{}, images interface{}) *MockProduct_CreateImages_Call {
	return &MockProduct_CreateImages_Call{Call: _e.mock.On("CreateImages", tx, productID, images)}
}

func (_c *MockProduct_CreateImages_Call) Run(run func(tx pgx.Tx, productID int, images []struct {
	url   string
	order int
})) *MockProduct_CreateImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []struct {
			url   string
			order int
		}
		if args[2] != nil {
			arg2 = args[2].([]struct {
				url   string
				order int
			})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProduct_CreateImages_Call) Return(productImages *[]domain.ProductImage, err error) *MockProduct_CreateImages_Call {
	_c.Call.Return(productImages, err)
	return _c
}

func (_c *MockProduct_CreateImages_Call) RunAndReturn(run func(tx pgx.Tx, productID int, images []struct {
	url   string
	order int
}) (*[]domain.ProductImage, error)) *MockProduct_CreateImages_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOptionValues provides a mock function for the type MockProduct
func (_mock *MockProduct) CreateOptionValues(tx pgx.Tx, optionID int, values []struct{ value string }) (*[]domain.OptionValue, error) {
	ret := _mock.Called(tx, optionID, values)

	if len(ret) == 0 {
		panic("no return value specified for CreateOptionValues")
	}

	var r0 *[]domain.OptionValue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, []struct{ value string }) (*[]domain.OptionValue, error)); ok {
		return returnFunc(tx, optionID, values)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, []struct{ value string }) *[]domain.OptionValue); ok {
		r0 = returnFunc(tx, optionID, values)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.OptionValue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, int, []struct{ value string }) error); ok {
		r1 = returnFunc(tx, optionID, values)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProduct_CreateOptionValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOptionValues'
type MockProduct_CreateOptionValues_Call struct {
	*mock.Call
}

// CreateOptionValues is a helper method to define mock.On call
//   - tx pgx.Tx
//   - optionID int
//   - values []struct{value string}
func (_e *MockProduct_Expecter) CreateOptionValues(tx interface{}, optionID interface{}, values interface{}) *MockProduct_CreateOptionValues_Call {
	return &MockProduct_CreateOptionValues_Call{Call: _e.mock.On("CreateOptionValues", tx, optionID, values)}
}

func (_c *MockProduct_CreateOptionValues_Call) Run(run func(tx pgx.Tx, optionID int, values []struct{ value string })) *MockProduct_CreateOptionValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []struct{ value string }
		if args[2] != nil {
			arg2 = args[2].([]struct{ value string })
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProduct_CreateOptionValues_Call) Return(optionValues *[]domain.OptionValue, err error) *MockProduct_CreateOptionValues_Call {
	_c.Call.Return(optionValues, err)
	return _c
}

func (_c *MockProduct_CreateOptionValues_Call) RunAndReturn(run func(tx pgx.Tx, optionID int, values []struct{ value string }) (*[]domain.OptionValue, error)) *MockProduct_CreateOptionValues_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOptions provides a mock function for the type MockProduct
func (_mock *MockProduct) CreateOptions(tx pgx.Tx, productID int, options []struct {
	name   string
	values []string
}) (*[]domain.Option, error) {
	ret := _mock.Called(tx, productID, options)

	if len(ret) == 0 {
		panic("no return value specified for CreateOptions")
	}

	var r0 *[]domain.Option
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, []struct {
		name   string
		values []string
	}) (*[]domain.Option, error)); ok {
		return returnFunc(tx, productID, options)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, []struct {
		name   string
		values []string
	}) *[]domain.Option); ok {
		r0 = returnFunc(tx, productID, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.Option)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, int, []struct {
		name   string
		values []string
	}) error); ok {
		r1 = returnFunc(tx, productID, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProduct_CreateOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOptions'
type MockProduct_CreateOptions_Call struct {
	*mock.Call
}

// CreateOptions is a helper method to define mock.On call
//   - tx pgx.Tx
//   - productID int
//   - options []struct{name string; values []string}
func (_e *MockProduct_Expecter) CreateOptions(tx interface{}, productID interface{}, options interface{}) *MockProduct_CreateOptions_Call {
	return &MockProduct_CreateOptions_Call{Call: _e.mock.On("CreateOptions", tx, productID, options)}
}

func (_c *MockProduct_CreateOptions_Call) Run(run func(tx pgx.Tx, productID int, options []struct {
	name   string
	values []string
})) *MockProduct_CreateOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []struct {
			name   string
			values []string
		}
		if args[2] != nil {
			arg2 = args[2].([]struct {
				name   string
				values []string
			})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProduct_CreateOptions_Call) Return(options1 *[]domain.Option, err error) *MockProduct_CreateOptions_Call {
	_c.Call.Return(options1, err)
	return _c
}

func (_c *MockProduct_CreateOptions_Call) RunAndReturn(run func(tx pgx.Tx, productID int, options []struct {
	name   string
	values []string
}) (*[]domain.Option, error)) *MockProduct_CreateOptions_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVariantImages provides a mock function for the type MockProduct
func (_mock *MockProduct) CreateVariantImages(tx pgx.Tx, variantID int, images []struct {
	url   string
	order int
}) (*[]domain.ProductImage, error) {
	ret := _mock.Called(tx, variantID, images)

	if len(ret) == 0 {
		panic("no return value specified for CreateVariantImages")
	}

	var r0 *[]domain.ProductImage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, []struct {
		url   string
		order int
	}) (*[]domain.ProductImage, error)); ok {
		return returnFunc(tx, variantID, images)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, []struct {
		url   string
		order int
	}) *[]domain.ProductImage); ok {
		r0 = returnFunc(tx, variantID, images)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.ProductImage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, int, []struct {
		url   string
		order int
	}) error); ok {
		r1 = returnFunc(tx, variantID, images)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProduct_CreateVariantImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVariantImages'
type MockProduct_CreateVariantImages_Call struct {
	*mock.Call
}

// CreateVariantImages is a helper method to define mock.On call
//   - tx pgx.Tx
//   - variantID int
//   - images []struct{url string; order int}
func (_e *MockProduct_Expecter) CreateVariantImages(tx interface{}, variantID interface{}, images interface{}) *MockProduct_CreateVariantImages_Call {
	return &MockProduct_CreateVariantImages_Call{Call: _e.mock.On("CreateVariantImages", tx, variantID, images)}
}

func (_c *MockProduct_CreateVariantImages_Call) Run(run func(tx pgx.Tx, variantID int, images []struct {
	url   string
	order int
})) *MockProduct_CreateVariantImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []struct {
			url   string
			order int
		}
		if args[2] != nil {
			arg2 = args[2].([]struct {
				url   string
				order int
			})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProduct_CreateVariantImages_Call) Return(productImages *[]domain.ProductImage, err error) *MockProduct_CreateVariantImages_Call {
	_c.Call.Return(productImages, err)
	return _c
}

func (_c *MockProduct_CreateVariantImages_Call) RunAndReturn(run func(tx pgx.Tx, variantID int, images []struct {
	url   string
	order int
}) (*[]domain.ProductImage, error)) *MockProduct_CreateVariantImages_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVariants provides a mock function for the type MockProduct
func (_mock *MockProduct) CreateVariants(tx pgx.Tx, productID int, variants []struct {
	sku            string
	price          int64
	quantity       int
	optionValueIDs []int
}) (*[]domain.ProductVariant, error) {
	ret := _mock.Called(tx, productID, variants)

	if len(ret) == 0 {
		panic("no return value specified for CreateVariants")
	}

	var r0 *[]domain.ProductVariant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, []struct {
		sku            string
		price          int64
		quantity       int
		optionValueIDs []int
	}) (*[]domain.ProductVariant, error)); ok {
		return returnFunc(tx, productID, variants)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, []struct {
		sku            string
		price          int64
		quantity       int
		optionValueIDs []int
	}) *[]domain.ProductVariant); ok {
		r0 = returnFunc(tx, productID, variants)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.ProductVariant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, int, []struct {
		sku            string
		price          int64
		quantity       int
		optionValueIDs []int
	}) error); ok {
		r1 = returnFunc(tx, productID, variants)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProduct_CreateVariants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVariants'
type MockProduct_CreateVariants_Call struct {
	*mock.Call
}

// CreateVariants is a helper method to define mock.On call
//   - tx pgx.Tx
//   - productID int
//   - variants []struct{sku string; price int64; quantity int; optionValueIDs []int}
func (_e *MockProduct_Expecter) CreateVariants(tx interface{}, productID interface{}, variants interface{}) *MockProduct_CreateVariants_Call {
	return &MockProduct_CreateVariants_Call{Call: _e.mock.On("CreateVariants", tx, productID, variants)}
}

func (_c *MockProduct_CreateVariants_Call) Run(run func(tx pgx.Tx, productID int, variants []struct {
	sku            string
	price          int64
	quantity       int
	optionValueIDs []int
})) *MockProduct_CreateVariants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []struct {
			sku            string
			price          int64
			quantity       int
			optionValueIDs []int
		}
		if args[2] != nil {
			arg2 = args[2].([]struct {
				sku            string
				price          int64
				quantity       int
				optionValueIDs []int
			})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProduct_CreateVariants_Call) Return(productVariants *[]domain.ProductVariant, err error) *MockProduct_CreateVariants_Call {
	_c.Call.Return(productVariants, err)
	return _c
}

func (_c *MockProduct_CreateVariants_Call) RunAndReturn(run func(tx pgx.Tx, productID int, variants []struct {
	sku            string
	price          int64
	quantity       int
	optionValueIDs []int
}) (*[]domain.ProductVariant, error)) *MockProduct_CreateVariants_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockProduct
func (_mock *MockProduct) Delete(tx pgx.Tx, productID int) error {
	ret := _mock.Called(tx, productID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int) error); ok {
		r0 = returnFunc(tx, productID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProduct_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProduct_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - tx pgx.Tx
//   - productID int
func (_e *MockProduct_Expecter) Delete(tx interface{}, productID interface{}) *MockProduct_Delete_Call {
	return &MockProduct_Delete_Call{Call: _e.mock.On("Delete", tx, productID)}
}

func (_c *MockProduct_Delete_Call) Run(run func(tx pgx.Tx, productID int)) *MockProduct_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProduct_Delete_Call) Return(err error) *MockProduct_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProduct_Delete_Call) RunAndReturn(run func(tx pgx.Tx, productID int) error) *MockProduct_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockProduct
func (_mock *MockProduct) Get(tx pgx.Tx, productID int) (*domain.Product, error) {
	ret := _mock.Called(tx, productID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int) (*domain.Product, error)); ok {
		return returnFunc(tx, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int) *domain.Product); ok {
		r0 = returnFunc(tx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, int) error); ok {
		r1 = returnFunc(tx, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProduct_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockProduct_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - tx pgx.Tx
//   - productID int
func (_e *MockProduct_Expecter) Get(tx interface{}, productID interface{}) *MockProduct_Get_Call {
	return &MockProduct_Get_Call{Call: _e.mock.On("Get", tx, productID)}
}

func (_c *MockProduct_Get_Call) Run(run func(tx pgx.Tx, productID int)) *MockProduct_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProduct_Get_Call) Return(product *domain.Product, err error) *MockProduct_Get_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockProduct_Get_Call) RunAndReturn(run func(tx pgx.Tx, productID int) (*domain.Product, error)) *MockProduct_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockProduct
func (_mock *MockProduct) List(tx pgx.Tx, ids *[]int, search *string, min_price *int64, max_price *int64, rating *float64, category_ids *[]int, deleted string, sort_rating *string, sort_price *string, limit int, offset int) (*[]domain.Product, error) {
	ret := _mock.Called(tx, ids, search, min_price, max_price, rating, category_ids, deleted, sort_rating, sort_price, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *[]domain.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, *[]int, *string, *int64, *int64, *float64, *[]int, string, *string, *string, int, int) (*[]domain.Product, error)); ok {
		return returnFunc(tx, ids, search, min_price, max_price, rating, category_ids, deleted, sort_rating, sort_price, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, *[]int, *string, *int64, *int64, *float64, *[]int, string, *string, *string, int, int) *[]domain.Product); ok {
		r0 = returnFunc(tx, ids, search, min_price, max_price, rating, category_ids, deleted, sort_rating, sort_price, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, *[]int, *string, *int64, *int64, *float64, *[]int, string, *string, *string, int, int) error); ok {
		r1 = returnFunc(tx, ids, search, min_price, max_price, rating, category_ids, deleted, sort_rating, sort_price, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProduct_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockProduct_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - tx pgx.Tx
//   - ids *[]int
//   - search *string
//   - min_price *int64
//   - max_price *int64
//   - rating *float64
//   - category_ids *[]int
//   - deleted string
//   - sort_rating *string
//   - sort_price *string
//   - limit int
//   - offset int
func (_e *MockProduct_Expecter) List(tx interface{}, ids interface{}, search interface{}, min_price interface{}, max_price interface{}, rating interface{}, category_ids interface{}, deleted interface{}, sort_rating interface{}, sort_price interface{}, limit interface{}, offset interface{}) *MockProduct_List_Call {
	return &MockProduct_List_Call{Call: _e.mock.On("List", tx, ids, search, min_price, max_price, rating, category_ids, deleted, sort_rating, sort_price, limit, offset)}
}

func (_c *MockProduct_List_Call) Run(run func(tx pgx.Tx, ids *[]int, search *string, min_price *int64, max_price *int64, rating *float64, category_ids *[]int, deleted string, sort_rating *string, sort_price *string, limit int, offset int)) *MockProduct_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 *[]int
		if args[1] != nil {
			arg1 = args[1].(*[]int)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *int64
		if args[3] != nil {
			arg3 = args[3].(*int64)
		}
		var arg4 *int64
		if args[4] != nil {
			arg4 = args[4].(*int64)
		}
		var arg5 *float64
		if args[5] != nil {
			arg5 = args[5].(*float64)
		}
		var arg6 *[]int
		if args[6] != nil {
			arg6 = args[6].(*[]int)
		}
		var arg7 string
		if args[7] != nil {
			arg7 = args[7].(string)
		}
		var arg8 *string
		if args[8] != nil {
			arg8 = args[8].(*string)
		}
		var arg9 *string
		if args[9] != nil {
			arg9 = args[9].(*string)
		}
		var arg10 int
		if args[10] != nil {
			arg10 = args[10].(int)
		}
		var arg11 int
		if args[11] != nil {
			arg11 = args[11].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
			arg8,
			arg9,
			arg10,
			arg11,
		)
	})
	return _c
}

func (_c *MockProduct_List_Call) Return(products *[]domain.Product, err error) *MockProduct_List_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *MockProduct_List_Call) RunAndReturn(run func(tx pgx.Tx, ids *[]int, search *string, min_price *int64, max_price *int64, rating *float64, category_ids *[]int, deleted string, sort_rating *string, sort_price *string, limit int, offset int) (*[]domain.Product, error)) *MockProduct_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockProduct
func (_mock *MockProduct) Update(tx pgx.Tx, productID int, name *string, description *string, categoryID *int) (*domain.Product, error) {
	ret := _mock.Called(tx, productID, name, description, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, *string, *string, *int) (*domain.Product, error)); ok {
		return returnFunc(tx, productID, name, description, categoryID)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, *string, *string, *int) *domain.Product); ok {
		r0 = returnFunc(tx, productID, name, description, categoryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, int, *string, *string, *int) error); ok {
		r1 = returnFunc(tx, productID, name, description, categoryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProduct_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProduct_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - tx pgx.Tx
//   - productID int
//   - name *string
//   - description *string
//   - categoryID *int
func (_e *MockProduct_Expecter) Update(tx interface{}, productID interface{}, name interface{}, description interface{}, categoryID interface{}) *MockProduct_Update_Call {
	return &MockProduct_Update_Call{Call: _e.mock.On("Update", tx, productID, name, description, categoryID)}
}

func (_c *MockProduct_Update_Call) Run(run func(tx pgx.Tx, productID int, name *string, description *string, categoryID *int)) *MockProduct_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		var arg4 *int
		if args[4] != nil {
			arg4 = args[4].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockProduct_Update_Call) Return(product *domain.Product, err error) *MockProduct_Update_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockProduct_Update_Call) RunAndReturn(run func(tx pgx.Tx, productID int, name *string, description *string, categoryID *int) (*domain.Product, error)) *MockProduct_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOptionValues provides a mock function for the type MockProduct
func (_mock *MockProduct) UpdateOptionValues(tx pgx.Tx, optionValues []struct {
	id    int
	value string
}) error {
	ret := _mock.Called(tx, optionValues)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOptionValues")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, []struct {
		id    int
		value string
	}) error); ok {
		r0 = returnFunc(tx, optionValues)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProduct_UpdateOptionValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOptionValues'
type MockProduct_UpdateOptionValues_Call struct {
	*mock.Call
}

// UpdateOptionValues is a helper method to define mock.On call
//   - tx pgx.Tx
//   - optionValues []struct{id int; value string}
func (_e *MockProduct_Expecter) UpdateOptionValues(tx interface{}, optionValues interface{}) *MockProduct_UpdateOptionValues_Call {
	return &MockProduct_UpdateOptionValues_Call{Call: _e.mock.On("UpdateOptionValues", tx, optionValues)}
}

func (_c *MockProduct_UpdateOptionValues_Call) Run(run func(tx pgx.Tx, optionValues []struct {
	id    int
	value string
})) *MockProduct_UpdateOptionValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 []struct {
			id    int
			value string
		}
		if args[1] != nil {
			arg1 = args[1].([]struct {
				id    int
				value string
			})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProduct_UpdateOptionValues_Call) Return(err error) *MockProduct_UpdateOptionValues_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProduct_UpdateOptionValues_Call) RunAndReturn(run func(tx pgx.Tx, optionValues []struct {
	id    int
	value string
}) error) *MockProduct_UpdateOptionValues_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOptions provides a mock function for the type MockProduct
func (_mock *MockProduct) UpdateOptions(tx pgx.Tx, options []struct {
	id   int
	name string
}) error {
	ret := _mock.Called(tx, options)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOptions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, []struct {
		id   int
		name string
	}) error); ok {
		r0 = returnFunc(tx, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProduct_UpdateOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOptions'
type MockProduct_UpdateOptions_Call struct {
	*mock.Call
}

// UpdateOptions is a helper method to define mock.On call
//   - tx pgx.Tx
//   - options []struct{id int; name string}
func (_e *MockProduct_Expecter) UpdateOptions(tx interface{}, options interface{}) *MockProduct_UpdateOptions_Call {
	return &MockProduct_UpdateOptions_Call{Call: _e.mock.On("UpdateOptions", tx, options)}
}

func (_c *MockProduct_UpdateOptions_Call) Run(run func(tx pgx.Tx, options []struct {
	id   int
	name string
})) *MockProduct_UpdateOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 []struct {
			id   int
			name string
		}
		if args[1] != nil {
			arg1 = args[1].([]struct {
				id   int
				name string
			})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProduct_UpdateOptions_Call) Return(err error) *MockProduct_UpdateOptions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProduct_UpdateOptions_Call) RunAndReturn(run func(tx pgx.Tx, options []struct {
	id   int
	name string
}) error) *MockProduct_UpdateOptions_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateVariant provides a mock function for the type MockProduct
func (_mock *MockProduct) UpdateVariant(tx pgx.Tx, variantID int, price *int64, quantity *int) (*domain.ProductVariant, error) {
	ret := _mock.Called(tx, variantID, price, quantity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVariant")
	}

	var r0 *domain.ProductVariant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, *int64, *int) (*domain.ProductVariant, error)); ok {
		return returnFunc(tx, variantID, price, quantity)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, *int64, *int) *domain.ProductVariant); ok {
		r0 = returnFunc(tx, variantID, price, quantity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProductVariant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, int, *int64, *int) error); ok {
		r1 = returnFunc(tx, variantID, price, quantity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProduct_UpdateVariant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateVariant'
type MockProduct_UpdateVariant_Call struct {
	*mock.Call
}

// UpdateVariant is a helper method to define mock.On call
//   - tx pgx.Tx
//   - variantID int
//   - price *int64
//   - quantity *int
func (_e *MockProduct_Expecter) UpdateVariant(tx interface{}, variantID interface{}, price interface{}, quantity interface{}) *MockProduct_UpdateVariant_Call {
	return &MockProduct_UpdateVariant_Call{Call: _e.mock.On("UpdateVariant", tx, variantID, price, quantity)}
}

func (_c *MockProduct_UpdateVariant_Call) Run(run func(tx pgx.Tx, variantID int, price *int64, quantity *int)) *MockProduct_UpdateVariant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *int64
		if args[2] != nil {
			arg2 = args[2].(*int64)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProduct_UpdateVariant_Call) Return(productVariant *domain.ProductVariant, err error) *MockProduct_UpdateVariant_Call {
	_c.Call.Return(productVariant, err)
	return _c
}

func (_c *MockProduct_UpdateVariant_Call) RunAndReturn(run func(tx pgx.Tx, variantID int, price *int64, quantity *int) (*domain.ProductVariant, error)) *MockProduct_UpdateVariant_Call {
	_c.Call.Return(run)
	return _c
}
