// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProduct creates a new instance of MockProduct. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProduct(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProduct {
	mock := &MockProduct{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProduct is an autogenerated mock type for the Product type
type MockProduct struct {
	mock.Mock
}

type MockProduct_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProduct) EXPECT() *MockProduct_Expecter {
	return &MockProduct_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockProduct
func (_mock *MockProduct) Create(tx pgx.Tx, name string, description string, attributeValueIDs []int, categoryID int) (int, error) {
	ret := _mock.Called(tx, name, description, attributeValueIDs, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, string, string, []int, int) (int, error)); ok {
		return returnFunc(tx, name, description, attributeValueIDs, categoryID)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, string, string, []int, int) int); ok {
		r0 = returnFunc(tx, name, description, attributeValueIDs, categoryID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, string, string, []int, int) error); ok {
		r1 = returnFunc(tx, name, description, attributeValueIDs, categoryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProduct_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProduct_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - tx pgx.Tx
//   - name string
//   - description string
//   - attributeValueIDs []int
//   - categoryID int
func (_e *MockProduct_Expecter) Create(tx interface{}, name interface{}, description interface{}, attributeValueIDs interface{}, categoryID interface{}) *MockProduct_Create_Call {
	return &MockProduct_Create_Call{Call: _e.mock.On("Create", tx, name, description, attributeValueIDs, categoryID)}
}

func (_c *MockProduct_Create_Call) Run(run func(tx pgx.Tx, name string, description string, attributeValueIDs []int, categoryID int)) *MockProduct_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []int
		if args[3] != nil {
			arg3 = args[3].([]int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockProduct_Create_Call) Return(n int, err error) *MockProduct_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockProduct_Create_Call) RunAndReturn(run func(tx pgx.Tx, name string, description string, attributeValueIDs []int, categoryID int) (int, error)) *MockProduct_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateImages provides a mock function for the type MockProduct
func (_mock *MockProduct) CreateImages() {
	_mock.Called()
	return
}

// MockProduct_CreateImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateImages'
type MockProduct_CreateImages_Call struct {
	*mock.Call
}

// CreateImages is a helper method to define mock.On call
func (_e *MockProduct_Expecter) CreateImages() *MockProduct_CreateImages_Call {
	return &MockProduct_CreateImages_Call{Call: _e.mock.On("CreateImages")}
}

func (_c *MockProduct_CreateImages_Call) Run(run func()) *MockProduct_CreateImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProduct_CreateImages_Call) Return() *MockProduct_CreateImages_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProduct_CreateImages_Call) RunAndReturn(run func()) *MockProduct_CreateImages_Call {
	_c.Run(run)
	return _c
}

// CreateOptions provides a mock function for the type MockProduct
func (_mock *MockProduct) CreateOptions(tx pgx.Tx, productID int, options []struct {
	name   string
	values []string
}) (int, error) {
	ret := _mock.Called(tx, productID, options)

	if len(ret) == 0 {
		panic("no return value specified for CreateOptions")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, []struct {
		name   string
		values []string
	}) (int, error)); ok {
		return returnFunc(tx, productID, options)
	}
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx, int, []struct {
		name   string
		values []string
	}) int); ok {
		r0 = returnFunc(tx, productID, options)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(pgx.Tx, int, []struct {
		name   string
		values []string
	}) error); ok {
		r1 = returnFunc(tx, productID, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProduct_CreateOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOptions'
type MockProduct_CreateOptions_Call struct {
	*mock.Call
}

// CreateOptions is a helper method to define mock.On call
//   - tx pgx.Tx
//   - productID int
//   - options []struct{name string; values []string}
func (_e *MockProduct_Expecter) CreateOptions(tx interface{}, productID interface{}, options interface{}) *MockProduct_CreateOptions_Call {
	return &MockProduct_CreateOptions_Call{Call: _e.mock.On("CreateOptions", tx, productID, options)}
}

func (_c *MockProduct_CreateOptions_Call) Run(run func(tx pgx.Tx, productID int, options []struct {
	name   string
	values []string
})) *MockProduct_CreateOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []struct {
			name   string
			values []string
		}
		if args[2] != nil {
			arg2 = args[2].([]struct {
				name   string
				values []string
			})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProduct_CreateOptions_Call) Return(n int, err error) *MockProduct_CreateOptions_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockProduct_CreateOptions_Call) RunAndReturn(run func(tx pgx.Tx, productID int, options []struct {
	name   string
	values []string
}) (int, error)) *MockProduct_CreateOptions_Call {
	_c.Call.Return(run)
	return _c
}
