// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"backend/internal/domain"

	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUser creates a new instance of MockUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUser {
	mock := &MockUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUser is an autogenerated mock type for the User type
type MockUser struct {
	mock.Mock
}

type MockUser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUser) EXPECT() *MockUser_Expecter {
	return &MockUser_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUser
func (_mock *MockUser) Create(tx *pgx.Tx, id string) (*domain.User, error) {
	ret := _mock.Called(tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*pgx.Tx, string) (*domain.User, error)); ok {
		return returnFunc(tx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(*pgx.Tx, string) *domain.User); ok {
		r0 = returnFunc(tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*pgx.Tx, string) error); ok {
		r1 = returnFunc(tx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUser_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUser_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - tx *pgx.Tx
//   - id string
func (_e *MockUser_Expecter) Create(tx interface{}, id interface{}) *MockUser_Create_Call {
	return &MockUser_Create_Call{Call: _e.mock.On("Create", tx, id)}
}

func (_c *MockUser_Create_Call) Run(run func(tx *pgx.Tx, id string)) *MockUser_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(*pgx.Tx)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUser_Create_Call) Return(user *domain.User, err error) *MockUser_Create_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUser_Create_Call) RunAndReturn(run func(tx *pgx.Tx, id string) (*domain.User, error)) *MockUser_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockUser
func (_mock *MockUser) Get(tx *pgx.Tx, userID string) (*domain.User, error) {
	ret := _mock.Called(tx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*pgx.Tx, string) (*domain.User, error)); ok {
		return returnFunc(tx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(*pgx.Tx, string) *domain.User); ok {
		r0 = returnFunc(tx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*pgx.Tx, string) error); ok {
		r1 = returnFunc(tx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUser_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUser_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - tx *pgx.Tx
//   - userID string
func (_e *MockUser_Expecter) Get(tx interface{}, userID interface{}) *MockUser_Get_Call {
	return &MockUser_Get_Call{Call: _e.mock.On("Get", tx, userID)}
}

func (_c *MockUser_Get_Call) Run(run func(tx *pgx.Tx, userID string)) *MockUser_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(*pgx.Tx)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUser_Get_Call) Return(user *domain.User, err error) *MockUser_Get_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUser_Get_Call) RunAndReturn(run func(tx *pgx.Tx, userID string) (*domain.User, error)) *MockUser_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetCart provides a mock function for the type MockUser
func (_mock *MockUser) GetCart(tx *pgx.Tx, userID string) (*Cart, error) {
	ret := _mock.Called(tx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCart")
	}

	var r0 *Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*pgx.Tx, string) (*Cart, error)); ok {
		return returnFunc(tx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(*pgx.Tx, string) *Cart); ok {
		r0 = returnFunc(tx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*pgx.Tx, string) error); ok {
		r1 = returnFunc(tx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUser_GetCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCart'
type MockUser_GetCart_Call struct {
	*mock.Call
}

// GetCart is a helper method to define mock.On call
//   - tx *pgx.Tx
//   - userID string
func (_e *MockUser_Expecter) GetCart(tx interface{}, userID interface{}) *MockUser_GetCart_Call {
	return &MockUser_GetCart_Call{Call: _e.mock.On("GetCart", tx, userID)}
}

func (_c *MockUser_GetCart_Call) Run(run func(tx *pgx.Tx, userID string)) *MockUser_GetCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(*pgx.Tx)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUser_GetCart_Call) Return(cart *Cart, err error) *MockUser_GetCart_Call {
	_c.Call.Return(cart, err)
	return _c
}

func (_c *MockUser_GetCart_Call) RunAndReturn(run func(tx *pgx.Tx, userID string) (*Cart, error)) *MockUser_GetCart_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockUser
func (_mock *MockUser) List(tx *pgx.Tx, limit int, offset int) (*[]domain.User, error) {
	ret := _mock.Called(tx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *[]domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*pgx.Tx, int, int) (*[]domain.User, error)); ok {
		return returnFunc(tx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(*pgx.Tx, int, int) *[]domain.User); ok {
		r0 = returnFunc(tx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*pgx.Tx, int, int) error); ok {
		r1 = returnFunc(tx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUser_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUser_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - tx *pgx.Tx
//   - limit int
//   - offset int
func (_e *MockUser_Expecter) List(tx interface{}, limit interface{}, offset interface{}) *MockUser_List_Call {
	return &MockUser_List_Call{Call: _e.mock.On("List", tx, limit, offset)}
}

func (_c *MockUser_List_Call) Run(run func(tx *pgx.Tx, limit int, offset int)) *MockUser_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(*pgx.Tx)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUser_List_Call) Return(users *[]domain.User, err error) *MockUser_List_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUser_List_Call) RunAndReturn(run func(tx *pgx.Tx, limit int, offset int) (*[]domain.User, error)) *MockUser_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUser
func (_mock *MockUser) Update(tx *pgx.Tx, userID string, firstName *string, lastName *string, email *string, dateOfBirth *string, phoneNumber *string, address *string) (*domain.User, error) {
	ret := _mock.Called(tx, userID, firstName, lastName, email, dateOfBirth, phoneNumber, address)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*pgx.Tx, string, *string, *string, *string, *string, *string, *string) (*domain.User, error)); ok {
		return returnFunc(tx, userID, firstName, lastName, email, dateOfBirth, phoneNumber, address)
	}
	if returnFunc, ok := ret.Get(0).(func(*pgx.Tx, string, *string, *string, *string, *string, *string, *string) *domain.User); ok {
		r0 = returnFunc(tx, userID, firstName, lastName, email, dateOfBirth, phoneNumber, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*pgx.Tx, string, *string, *string, *string, *string, *string, *string) error); ok {
		r1 = returnFunc(tx, userID, firstName, lastName, email, dateOfBirth, phoneNumber, address)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUser_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUser_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - tx *pgx.Tx
//   - userID string
//   - firstName *string
//   - lastName *string
//   - email *string
//   - dateOfBirth *string
//   - phoneNumber *string
//   - address *string
func (_e *MockUser_Expecter) Update(tx interface{}, userID interface{}, firstName interface{}, lastName interface{}, email interface{}, dateOfBirth interface{}, phoneNumber interface{}, address interface{}) *MockUser_Update_Call {
	return &MockUser_Update_Call{Call: _e.mock.On("Update", tx, userID, firstName, lastName, email, dateOfBirth, phoneNumber, address)}
}

func (_c *MockUser_Update_Call) Run(run func(tx *pgx.Tx, userID string, firstName *string, lastName *string, email *string, dateOfBirth *string, phoneNumber *string, address *string)) *MockUser_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(*pgx.Tx)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		var arg5 *string
		if args[5] != nil {
			arg5 = args[5].(*string)
		}
		var arg6 *string
		if args[6] != nil {
			arg6 = args[6].(*string)
		}
		var arg7 *string
		if args[7] != nil {
			arg7 = args[7].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
		)
	})
	return _c
}

func (_c *MockUser_Update_Call) Return(user *domain.User, err error) *MockUser_Update_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUser_Update_Call) RunAndReturn(run func(tx *pgx.Tx, userID string, firstName *string, lastName *string, email *string, dateOfBirth *string, phoneNumber *string, address *string) (*domain.User, error)) *MockUser_Update_Call {
	_c.Call.Return(run)
	return _c
}
