// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"backend/config"
	"backend/internal/application"
	"backend/internal/client"
	"backend/internal/delivery/http"
	"backend/internal/domain"
	"backend/internal/infrastructure/cacheredis"
	"backend/internal/infrastructure/objectstorages3"
	"backend/internal/infrastructure/repositorypostgres"
	"backend/internal/service"
	"backend/pkg/logger"
	"context"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context) *http.Server {
	engine := client.NewGin()
	server := config.NewServer()
	goCloak := client.NewKeycloak(ctx, server)
	redisClient := client.NewRedis(ctx, server)
	s3Client := client.NewS3(ctx, server)
	pool := client.NewDBConnection(ctx, server)
	healthHandlerImpl := http.ProvideHealthHandler(goCloak, redisClient, s3Client, pool, server)
	metricMiddlewareImpl := http.ProvideMetricMiddleware()
	loggerConfig := logger.NewConfig(server)
	zapLogger := logger.New(loggerConfig)
	loggingMiddlewareImpl := http.ProvideLoggingMiddleware(zapLogger)
	ginAuthMiddleware := http.ProvideAuthMiddleware(goCloak, server)
	queries := client.NewDBQueries(pool)
	category := repositorypostgres.ProvideCategory(queries)
	validate := client.NewValidate()
	serviceCategory := service.ProvideCategory(validate)
	cacheredisCategory := cacheredis.ProvideCategory(redisClient)
	categoryImpl := application.ProvideCategory(category, serviceCategory, cacheredisCategory)
	categoryHandlerImpl := http.ProvideCategoryHandler(categoryImpl)
	attribute := repositorypostgres.ProvideAttribute(queries, pool)
	serviceAttribute := service.ProvideAttribute(validate)
	product := cacheredis.ProvideProduct(redisClient)
	presignClient := client.NewS3Presign(s3Client)
	objectstorages3Product := objectstorages3.ProvideProduct(s3Client, presignClient, server)
	repositorypostgresProduct := repositorypostgres.ProvideProduct(queries, pool)
	serviceProduct := service.ProvideProduct(validate)
	productImpl := application.ProvideProduct(attribute, serviceAttribute, category, product, objectstorages3Product, repositorypostgresProduct, serviceProduct)
	productHandlerImpl := http.ProvideProductHandler(productImpl)
	cacheredisAttribute := cacheredis.ProvideAttribute(redisClient)
	attributeImpl := application.ProvideAttribute(attribute, serviceAttribute, cacheredisAttribute)
	attributeHandlerImpl := http.ProvideAttributeHandler(attributeImpl)
	order := repositorypostgres.ProvideOrder(queries)
	serviceOrder := service.ProvideOrder(validate)
	orderImpl := application.ProvideOrder(order, serviceOrder)
	orderHandlerImpl := http.ProvideOrderHandler(orderImpl)
	review := repositorypostgres.ProvideReview(queries)
	serviceReview := service.ProvideReview(validate)
	cacheredisReview := cacheredis.ProvideReview(redisClient)
	reviewImpl := application.ProvideReview(review, serviceReview, cacheredisReview)
	reviewHandlerImpl := http.ProvideReviewHandler(reviewImpl)
	cart := repositorypostgres.ProvideCart(queries)
	serviceCart := service.ProvideCart(validate)
	cartImpl := application.ProvideCart(cart, serviceCart)
	cartHandlerImpl := http.ProvideCartHandler(cartImpl)
	ginRouter := http.ProvideRouter(healthHandlerImpl, metricMiddlewareImpl, loggingMiddlewareImpl, ginAuthMiddleware, categoryHandlerImpl, productHandlerImpl, attributeHandlerImpl, orderHandlerImpl, reviewHandlerImpl, cartHandlerImpl)
	authHandlerImpl := http.ProvideAuthHandler(server)
	httpServer := http.NewServer(engine, ginRouter, server, authHandlerImpl)
	return httpServer
}

// wire.go:

var ConfigSet = wire.NewSet(config.NewServer, logger.NewConfig)

var LoggerSet = wire.NewSet(logger.New)

var DbSet = wire.NewSet(client.NewDBConnection, client.NewDBQueries, client.NewDBTransactor)

var EngineSet = wire.NewSet(client.NewGin)

var ServiceSet = wire.NewSet(service.ProvideAttribute, wire.Bind(
	new(domain.AttributeService),
	new(*service.Attribute),
), service.ProvideCart, wire.Bind(
	new(domain.CartService),
	new(*service.Cart),
), service.ProvideCategory, wire.Bind(
	new(domain.CategoryService),
	new(*service.Category),
), service.ProvideOrder, wire.Bind(
	new(domain.OrderService),
	new(*service.Order),
), service.ProvideProduct, wire.Bind(
	new(domain.ProductService),
	new(*service.Product),
), service.ProvideReview, wire.Bind(
	new(domain.ReviewService),
	new(*service.Review),
),
)

var MiddlewareSet = wire.NewSet(http.ProvideAuthMiddleware, wire.Bind(
	new(http.AuthMiddleware),
	new(*http.GinAuthMiddleware),
), http.ProvideLoggingMiddleware, wire.Bind(
	new(http.LoggingMiddleware),
	new(*http.LoggingMiddlewareImpl),
), http.ProvideMetricMiddleware, wire.Bind(
	new(http.MetricMiddleware),
	new(*http.MetricMiddlewareImpl),
), http.ProvideRoleMiddleware, wire.Bind(
	new(http.RoleMiddleware),
	new(*http.RoleMiddlewareImpl),
),
)

var HandlerSet = wire.NewSet(http.ProvideAttributeHandler, wire.Bind(
	new(http.AttributeHandler),
	new(*http.AttributeHandlerImpl),
), http.ProvideAuthHandler, wire.Bind(
	new(http.AuthHandler),
	new(*http.AuthHandlerImpl),
), http.ProvideCategoryHandler, wire.Bind(
	new(http.CategoryHandler),
	new(*http.CategoryHandlerImpl),
), http.ProvideHealthHandler, wire.Bind(
	new(http.HealthHandler),
	new(*http.HealthHandlerImpl),
), http.ProvideOrderHandler, wire.Bind(
	new(http.OrderHandler),
	new(*http.OrderHandlerImpl),
), http.ProvideProductHandler, wire.Bind(
	new(http.ProductHandler),
	new(*http.ProductHandlerImpl),
), http.ProvideReviewHandler, wire.Bind(
	new(http.ReviewHandler),
	new(*http.ReviewHandlerImpl),
), http.ProvideCartHandler, wire.Bind(
	new(http.CartHandler),
	new(*http.CartHandlerImpl),
),
)

var ApplicationSet = wire.NewSet(application.ProvideAttribute, wire.Bind(
	new(application.Attribute),
	new(*application.AttributeImpl),
), application.ProvideCart, wire.Bind(
	new(application.Cart),
	new(*application.CartImpl),
), application.ProvideCategory, wire.Bind(
	new(application.Category),
	new(*application.CategoryImpl),
), application.ProvideOrder, wire.Bind(
	new(application.Order),
	new(*application.OrderImpl),
), application.ProvideProduct, wire.Bind(
	new(application.Product),
	new(*application.ProductImpl),
), application.ProvideReview, wire.Bind(
	new(application.Review),
	new(*application.ReviewImpl),
),
)

var RepositorySet = wire.NewSet(repositorypostgres.ProvideAttribute, wire.Bind(
	new(domain.AttributeRepository),
	new(*repositorypostgres.Attribute),
), repositorypostgres.ProvideCart, wire.Bind(
	new(domain.CartRepository),
	new(*repositorypostgres.Cart),
), repositorypostgres.ProvideCategory, wire.Bind(
	new(domain.CategoryRepository),
	new(*repositorypostgres.Category),
), repositorypostgres.ProvideOrder, wire.Bind(
	new(domain.OrderRepository),
	new(*repositorypostgres.Order),
), repositorypostgres.ProvideProduct, wire.Bind(
	new(domain.ProductRepository),
	new(*repositorypostgres.Product),
), repositorypostgres.ProvideReview, wire.Bind(
	new(domain.ReviewRepository),
	new(*repositorypostgres.Review),
),
)

var RouterSet = wire.NewSet(http.ProvideRouter, wire.Bind(
	new(http.Router),
	new(*http.GinRouter),
),
)

var ClientSet = wire.NewSet(client.NewKeycloak, client.NewRedis, client.NewS3, client.NewS3Presign, client.NewValidate)

var CacheSet = wire.NewSet(cacheredis.ProvideProduct, wire.Bind(
	new(application.ProductCache),
	new(*cacheredis.Product),
), cacheredis.ProvideReview, wire.Bind(
	new(application.ReviewCache),
	new(*cacheredis.Review),
), cacheredis.ProvideCategory, wire.Bind(
	new(application.CategoryCache),
	new(*cacheredis.Category),
), cacheredis.ProvideAttribute, wire.Bind(
	new(application.AttributeCache),
	new(*cacheredis.Attribute),
),
)

var ObjectStorageSet = wire.NewSet(objectstorages3.ProvideProduct, wire.Bind(
	new(application.ProductObjectStorage),
	new(*objectstorages3.Product),
),
)
