### Frontend Direct Access

# @prompt password
# @prompt username

POST http://localhost:8081/realms/electricilies/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password&
client_id=frontend&
client_secret=electricilies&
username={{username}}&
password={{password}}


### Introspect

# @prompt access_token

POST http://localhost:8081/realms/electricilies/protocol/openid-connect/token/introspect HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id=backend&
client_secret=electricilies&
token={{access_token}}
