services:
  db:
    image: postgres:18.0-trixie
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-electricilies}
      PGDATA: /data/postgres
    ports:
      - "${DB_PORT:-5432}:5432"
