keycloak_url            = "http://localhost:8081"
terraform_client_secret = "electricilies"
backend_client_secret = "electricilies"
frontend_client_secret = "electricilies"
frontend_root_url = "http://localhost:3000"
