// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countReviews = `-- name: CountReviews :one
SELECT
  COUNT(*) AS count
FROM
  reviews
LEFT JOIN order_items ON reviews.order_item_id = order_items.id
LEFT JOIN product_variants ON order_items.product_variant_id = product_variants.id
WHERE
  CASE
    WHEN $1::uuid[] IS NULL THEN TRUE
    ELSE reviews.id = ANY ($1::uuid[])
  END
  AND CASE
    WHEN $2::uuid[] IS NULL THEN TRUE
    ELSE reviews.order_item_id = ANY ($2::uuid[])
  END
  AND CASE
    WHEN $3::uuid[] IS NULL THEN TRUE
    ELSE product_variants.product_id = ANY ($3::uuid[])
  END
  AND CASE
    WHEN $4::text = 'exclude' THEN reviews.deleted_at IS NULL
    WHEN $4::text = 'only' THEN reviews.deleted_at IS NOT NULL
    WHEN $4::text = 'all' THEN TRUE
    ELSE reviews.deleted_at IS NOT NULL
  END
`

type CountReviewsParams struct {
	IDs          []uuid.UUID
	OrderItemIds []uuid.UUID
	ProductIDs   []uuid.UUID
	Deleted      string
}

func (q *Queries) CountReviews(ctx context.Context, arg CountReviewsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReviews,
		arg.IDs,
		arg.OrderItemIds,
		arg.ProductIDs,
		arg.Deleted,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getReview = `-- name: GetReview :one
SELECT
  id, rating, content, image_url, created_at, updated_at, deleted_at, user_id, order_item_id
FROM
  reviews
WHERE
  id = $1
  AND CASE
    WHEN $2::text = 'exclude' THEN deleted_at IS NULL
    WHEN $2::text = 'only' THEN deleted_at IS NOT NULL
    WHEN $2::text = 'all' THEN TRUE
    ELSE deleted_at IS NULL
  END
`

type GetReviewParams struct {
	ID      uuid.UUID
	Deleted string
}

func (q *Queries) GetReview(ctx context.Context, arg GetReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, getReview, arg.ID, arg.Deleted)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.Rating,
		&i.Content,
		&i.ImageURL,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.OrderItemID,
	)
	return i, err
}

const listReviews = `-- name: ListReviews :many
SELECT
  reviews.id, reviews.rating, reviews.content, reviews.image_url, reviews.created_at, reviews.updated_at, reviews.deleted_at, reviews.user_id, reviews.order_item_id
FROM
  reviews
LEFT JOIN order_items ON reviews.order_item_id = order_items.id
LEFT JOIN product_variants ON order_items.product_variant_id = product_variants.id
WHERE
  CASE
    WHEN $1::uuid[] IS NULL THEN TRUE
    ELSE reviews.id = ANY ($1::uuid[])
  END
  AND CASE
    WHEN $2::uuid[] IS NULL THEN TRUE
    ELSE reviews.order_item_id = ANY ($2::uuid[])
  END
  AND CASE
    WHEN $3::uuid[] IS NULL THEN TRUE
    ELSE product_variants.product_id = ANY ($3::uuid[])
  END
  AND CASE
    WHEN $4::text = 'exclude' THEN reviews.deleted_at IS NULL
    WHEN $4::text = 'only' THEN reviews.deleted_at IS NOT NULL
    WHEN $4::text = 'all' THEN TRUE
    ELSE reviews.deleted_at IS NOT NULL
  END
ORDER BY
  reviews.created_at DESC
OFFSET $5::integer
LIMIT NULLIF($6::integer, 0)
`

type ListReviewsParams struct {
	IDs          []uuid.UUID
	OrderItemIds []uuid.UUID
	ProductIDs   []uuid.UUID
	Deleted      string
	Offset       int32
	Limit        int32
}

func (q *Queries) ListReviews(ctx context.Context, arg ListReviewsParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviews,
		arg.IDs,
		arg.OrderItemIds,
		arg.ProductIDs,
		arg.Deleted,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Content,
			&i.ImageURL,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserID,
			&i.OrderItemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReview = `-- name: UpsertReview :exec
INSERT INTO reviews (
  id,
  rating,
  content,
  image_url,
  user_id,
  order_item_id,
  created_at,
  updated_at,
  deleted_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
ON CONFLICT (id) DO UPDATE SET
  rating = EXCLUDED.rating,
  content = EXCLUDED.content,
  image_url = EXCLUDED.image_url,
  user_id = EXCLUDED.user_id,
  order_item_id = EXCLUDED.order_item_id,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at,
  deleted_at = EXCLUDED.deleted_at
`

type UpsertReviewParams struct {
	ID          uuid.UUID
	Rating      int16
	Content     *string
	ImageURL    *string
	UserID      uuid.UUID
	OrderItemID uuid.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

func (q *Queries) UpsertReview(ctx context.Context, arg UpsertReviewParams) error {
	_, err := q.db.Exec(ctx, upsertReview,
		arg.ID,
		arg.Rating,
		arg.Content,
		arg.ImageURL,
		arg.UserID,
		arg.OrderItemID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}
