// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
  name
)
VALUES (
  $1
)
RETURNING
  id, name, created_at, updated_at, deleted_at
`

type CreateCategoryParams struct {
	Name string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
UPDATE
  categories
SET
  deleted_at = NOW()
WHERE
  deleted_at IS NULL
  AND id = $1
`

type DeleteCategoryParams struct {
	ID int32
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSuggestedCategories = `-- name: GetSuggestedCategories :many
SELECT
  id, name, created_at, updated_at, deleted_at
FROM
  categories
WHERE
  deleted_at IS NULL
  AND name ||| $1
ORDER BY
  pdb.score(id) DESC
LIMIT COALESCE($2::integer, 10)
`

type GetSuggestedCategoriesParams struct {
	Name  string
	Limit pgtype.Int4
}

func (q *Queries) GetSuggestedCategories(ctx context.Context, arg GetSuggestedCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, getSuggestedCategories, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT
  id, name, created_at, updated_at, deleted_at,
  COUNT(*) OVER() AS current_count,
  COUNT(*) AS total_count
FROM
  categories
WHERE
  deleted_at IS NULL
ORDER BY
  id DESC
OFFSET COALESCE($1::integer, 0)
LIMIT COALESCE($2::integer, 20)
`

type ListCategoriesParams struct {
	Offset pgtype.Int4
	Limit  pgtype.Int4
}

type ListCategoriesRow struct {
	ID           int32
	Name         string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
	CurrentCount int64
	TotalCount   int64
}

// TODO: Get category by name (paradedb)
func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CurrentCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE
  categories
SET
  name = $1,
  updated_at = NOW()
WHERE
  deleted_at IS NULL
  AND id = $2
RETURNING
  id, name, created_at, updated_at, deleted_at
`

type UpdateCategoryParams struct {
	Name string
	ID   int32
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.Name, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
