// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAttributeRepository creates a new instance of MockAttributeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttributeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttributeRepository {
	mock := &MockAttributeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAttributeRepository is an autogenerated mock type for the AttributeRepository type
type MockAttributeRepository struct {
	mock.Mock
}

type MockAttributeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttributeRepository) EXPECT() *MockAttributeRepository_Expecter {
	return &MockAttributeRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockAttributeRepository
func (_mock *MockAttributeRepository) Count(ctx context.Context, ids *[]uuid.UUID, deleted DeletedParam) (*int, error) {
	ret := _mock.Called(ctx, ids, deleted)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 *int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]uuid.UUID, DeletedParam) (*int, error)); ok {
		return returnFunc(ctx, ids, deleted)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]uuid.UUID, DeletedParam) *int); ok {
		r0 = returnFunc(ctx, ids, deleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *[]uuid.UUID, DeletedParam) error); ok {
		r1 = returnFunc(ctx, ids, deleted)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttributeRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockAttributeRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - ids *[]uuid.UUID
//   - deleted DeletedParam
func (_e *MockAttributeRepository_Expecter) Count(ctx interface{}, ids interface{}, deleted interface{}) *MockAttributeRepository_Count_Call {
	return &MockAttributeRepository_Count_Call{Call: _e.mock.On("Count", ctx, ids, deleted)}
}

func (_c *MockAttributeRepository_Count_Call) Run(run func(ctx context.Context, ids *[]uuid.UUID, deleted DeletedParam)) *MockAttributeRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *[]uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(*[]uuid.UUID)
		}
		var arg2 DeletedParam
		if args[2] != nil {
			arg2 = args[2].(DeletedParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAttributeRepository_Count_Call) Return(n *int, err error) *MockAttributeRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAttributeRepository_Count_Call) RunAndReturn(run func(ctx context.Context, ids *[]uuid.UUID, deleted DeletedParam) (*int, error)) *MockAttributeRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// CountValues provides a mock function for the type MockAttributeRepository
func (_mock *MockAttributeRepository) CountValues(ctx context.Context, attributeID *uuid.UUID, attributeValueIDs *[]uuid.UUID) (*int, error) {
	ret := _mock.Called(ctx, attributeID, attributeValueIDs)

	if len(ret) == 0 {
		panic("no return value specified for CountValues")
	}

	var r0 *int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, *[]uuid.UUID) (*int, error)); ok {
		return returnFunc(ctx, attributeID, attributeValueIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, *[]uuid.UUID) *int); ok {
		r0 = returnFunc(ctx, attributeID, attributeValueIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uuid.UUID, *[]uuid.UUID) error); ok {
		r1 = returnFunc(ctx, attributeID, attributeValueIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttributeRepository_CountValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountValues'
type MockAttributeRepository_CountValues_Call struct {
	*mock.Call
}

// CountValues is a helper method to define mock.On call
//   - ctx context.Context
//   - attributeID *uuid.UUID
//   - attributeValueIDs *[]uuid.UUID
func (_e *MockAttributeRepository_Expecter) CountValues(ctx interface{}, attributeID interface{}, attributeValueIDs interface{}) *MockAttributeRepository_CountValues_Call {
	return &MockAttributeRepository_CountValues_Call{Call: _e.mock.On("CountValues", ctx, attributeID, attributeValueIDs)}
}

func (_c *MockAttributeRepository_CountValues_Call) Run(run func(ctx context.Context, attributeID *uuid.UUID, attributeValueIDs *[]uuid.UUID)) *MockAttributeRepository_CountValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(*uuid.UUID)
		}
		var arg2 *[]uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*[]uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAttributeRepository_CountValues_Call) Return(n *int, err error) *MockAttributeRepository_CountValues_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAttributeRepository_CountValues_Call) RunAndReturn(run func(ctx context.Context, attributeID *uuid.UUID, attributeValueIDs *[]uuid.UUID) (*int, error)) *MockAttributeRepository_CountValues_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockAttributeRepository
func (_mock *MockAttributeRepository) Get(ctx context.Context, id uuid.UUID) (*Attribute, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *Attribute
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*Attribute, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *Attribute); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Attribute)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttributeRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAttributeRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAttributeRepository_Expecter) Get(ctx interface{}, id interface{}) *MockAttributeRepository_Get_Call {
	return &MockAttributeRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockAttributeRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAttributeRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttributeRepository_Get_Call) Return(attribute *Attribute, err error) *MockAttributeRepository_Get_Call {
	_c.Call.Return(attribute, err)
	return _c
}

func (_c *MockAttributeRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*Attribute, error)) *MockAttributeRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockAttributeRepository
func (_mock *MockAttributeRepository) List(ctx context.Context, ids *[]uuid.UUID, search *string, deleted DeletedParam, limit int, offset int) (*[]Attribute, error) {
	ret := _mock.Called(ctx, ids, search, deleted, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *[]Attribute
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]uuid.UUID, *string, DeletedParam, int, int) (*[]Attribute, error)); ok {
		return returnFunc(ctx, ids, search, deleted, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]uuid.UUID, *string, DeletedParam, int, int) *[]Attribute); ok {
		r0 = returnFunc(ctx, ids, search, deleted, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]Attribute)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *[]uuid.UUID, *string, DeletedParam, int, int) error); ok {
		r1 = returnFunc(ctx, ids, search, deleted, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttributeRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAttributeRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - ids *[]uuid.UUID
//   - search *string
//   - deleted DeletedParam
//   - limit int
//   - offset int
func (_e *MockAttributeRepository_Expecter) List(ctx interface{}, ids interface{}, search interface{}, deleted interface{}, limit interface{}, offset interface{}) *MockAttributeRepository_List_Call {
	return &MockAttributeRepository_List_Call{Call: _e.mock.On("List", ctx, ids, search, deleted, limit, offset)}
}

func (_c *MockAttributeRepository_List_Call) Run(run func(ctx context.Context, ids *[]uuid.UUID, search *string, deleted DeletedParam, limit int, offset int)) *MockAttributeRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *[]uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(*[]uuid.UUID)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 DeletedParam
		if args[3] != nil {
			arg3 = args[3].(DeletedParam)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockAttributeRepository_List_Call) Return(attributes *[]Attribute, err error) *MockAttributeRepository_List_Call {
	_c.Call.Return(attributes, err)
	return _c
}

func (_c *MockAttributeRepository_List_Call) RunAndReturn(run func(ctx context.Context, ids *[]uuid.UUID, search *string, deleted DeletedParam, limit int, offset int) (*[]Attribute, error)) *MockAttributeRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListValues provides a mock function for the type MockAttributeRepository
func (_mock *MockAttributeRepository) ListValues(ctx context.Context, attributeID *uuid.UUID, attributeValueIDs *[]uuid.UUID, search *string, deleted DeletedParam, limit int, offset int) (*[]AttributeValue, error) {
	ret := _mock.Called(ctx, attributeID, attributeValueIDs, search, deleted, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListValues")
	}

	var r0 *[]AttributeValue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, *[]uuid.UUID, *string, DeletedParam, int, int) (*[]AttributeValue, error)); ok {
		return returnFunc(ctx, attributeID, attributeValueIDs, search, deleted, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, *[]uuid.UUID, *string, DeletedParam, int, int) *[]AttributeValue); ok {
		r0 = returnFunc(ctx, attributeID, attributeValueIDs, search, deleted, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]AttributeValue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uuid.UUID, *[]uuid.UUID, *string, DeletedParam, int, int) error); ok {
		r1 = returnFunc(ctx, attributeID, attributeValueIDs, search, deleted, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttributeRepository_ListValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListValues'
type MockAttributeRepository_ListValues_Call struct {
	*mock.Call
}

// ListValues is a helper method to define mock.On call
//   - ctx context.Context
//   - attributeID *uuid.UUID
//   - attributeValueIDs *[]uuid.UUID
//   - search *string
//   - deleted DeletedParam
//   - limit int
//   - offset int
func (_e *MockAttributeRepository_Expecter) ListValues(ctx interface{}, attributeID interface{}, attributeValueIDs interface{}, search interface{}, deleted interface{}, limit interface{}, offset interface{}) *MockAttributeRepository_ListValues_Call {
	return &MockAttributeRepository_ListValues_Call{Call: _e.mock.On("ListValues", ctx, attributeID, attributeValueIDs, search, deleted, limit, offset)}
}

func (_c *MockAttributeRepository_ListValues_Call) Run(run func(ctx context.Context, attributeID *uuid.UUID, attributeValueIDs *[]uuid.UUID, search *string, deleted DeletedParam, limit int, offset int)) *MockAttributeRepository_ListValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(*uuid.UUID)
		}
		var arg2 *[]uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*[]uuid.UUID)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		var arg4 DeletedParam
		if args[4] != nil {
			arg4 = args[4].(DeletedParam)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		var arg6 int
		if args[6] != nil {
			arg6 = args[6].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockAttributeRepository_ListValues_Call) Return(attributeValues *[]AttributeValue, err error) *MockAttributeRepository_ListValues_Call {
	_c.Call.Return(attributeValues, err)
	return _c
}

func (_c *MockAttributeRepository_ListValues_Call) RunAndReturn(run func(ctx context.Context, attributeID *uuid.UUID, attributeValueIDs *[]uuid.UUID, search *string, deleted DeletedParam, limit int, offset int) (*[]AttributeValue, error)) *MockAttributeRepository_ListValues_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockAttributeRepository
func (_mock *MockAttributeRepository) Save(ctx context.Context, attribute Attribute) error {
	ret := _mock.Called(ctx, attribute)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Attribute) error); ok {
		r0 = returnFunc(ctx, attribute)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAttributeRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAttributeRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - attribute Attribute
func (_e *MockAttributeRepository_Expecter) Save(ctx interface{}, attribute interface{}) *MockAttributeRepository_Save_Call {
	return &MockAttributeRepository_Save_Call{Call: _e.mock.On("Save", ctx, attribute)}
}

func (_c *MockAttributeRepository_Save_Call) Run(run func(ctx context.Context, attribute Attribute)) *MockAttributeRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Attribute
		if args[1] != nil {
			arg1 = args[1].(Attribute)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttributeRepository_Save_Call) Return(err error) *MockAttributeRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAttributeRepository_Save_Call) RunAndReturn(run func(ctx context.Context, attribute Attribute) error) *MockAttributeRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
