// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAttributeRepository creates a new instance of MockAttributeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttributeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttributeRepository {
	mock := &MockAttributeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAttributeRepository is an autogenerated mock type for the AttributeRepository type
type MockAttributeRepository struct {
	mock.Mock
}

type MockAttributeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttributeRepository) EXPECT() *MockAttributeRepository_Expecter {
	return &MockAttributeRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockAttributeRepository
func (_mock *MockAttributeRepository) Count(ctx context.Context, ids *[]int, deleted string, limit int, offset int) (*int, error) {
	ret := _mock.Called(ctx, ids, deleted, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 *int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]int, string, int, int) (*int, error)); ok {
		return returnFunc(ctx, ids, deleted, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]int, string, int, int) *int); ok {
		r0 = returnFunc(ctx, ids, deleted, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *[]int, string, int, int) error); ok {
		r1 = returnFunc(ctx, ids, deleted, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttributeRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockAttributeRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - ids *[]int
//   - deleted string
//   - limit int
//   - offset int
func (_e *MockAttributeRepository_Expecter) Count(ctx interface{}, ids interface{}, deleted interface{}, limit interface{}, offset interface{}) *MockAttributeRepository_Count_Call {
	return &MockAttributeRepository_Count_Call{Call: _e.mock.On("Count", ctx, ids, deleted, limit, offset)}
}

func (_c *MockAttributeRepository_Count_Call) Run(run func(ctx context.Context, ids *[]int, deleted string, limit int, offset int)) *MockAttributeRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *[]int
		if args[1] != nil {
			arg1 = args[1].(*[]int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAttributeRepository_Count_Call) Return(n *int, err error) *MockAttributeRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAttributeRepository_Count_Call) RunAndReturn(run func(ctx context.Context, ids *[]int, deleted string, limit int, offset int) (*int, error)) *MockAttributeRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockAttributeRepository
func (_mock *MockAttributeRepository) Get(ctx context.Context, id int) (*Attribute, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *Attribute
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*Attribute, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *Attribute); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Attribute)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttributeRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAttributeRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockAttributeRepository_Expecter) Get(ctx interface{}, id interface{}) *MockAttributeRepository_Get_Call {
	return &MockAttributeRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockAttributeRepository_Get_Call) Run(run func(ctx context.Context, id int)) *MockAttributeRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttributeRepository_Get_Call) Return(attribute *Attribute, err error) *MockAttributeRepository_Get_Call {
	_c.Call.Return(attribute, err)
	return _c
}

func (_c *MockAttributeRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id int) (*Attribute, error)) *MockAttributeRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockAttributeRepository
func (_mock *MockAttributeRepository) List(ctx context.Context, ids *[]int, search *string, deleted string, limit int, offset int) (*[]Attribute, error) {
	ret := _mock.Called(ctx, ids, search, deleted, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *[]Attribute
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]int, *string, string, int, int) (*[]Attribute, error)); ok {
		return returnFunc(ctx, ids, search, deleted, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]int, *string, string, int, int) *[]Attribute); ok {
		r0 = returnFunc(ctx, ids, search, deleted, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]Attribute)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *[]int, *string, string, int, int) error); ok {
		r1 = returnFunc(ctx, ids, search, deleted, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttributeRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAttributeRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - ids *[]int
//   - search *string
//   - deleted string
//   - limit int
//   - offset int
func (_e *MockAttributeRepository_Expecter) List(ctx interface{}, ids interface{}, search interface{}, deleted interface{}, limit interface{}, offset interface{}) *MockAttributeRepository_List_Call {
	return &MockAttributeRepository_List_Call{Call: _e.mock.On("List", ctx, ids, search, deleted, limit, offset)}
}

func (_c *MockAttributeRepository_List_Call) Run(run func(ctx context.Context, ids *[]int, search *string, deleted string, limit int, offset int)) *MockAttributeRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *[]int
		if args[1] != nil {
			arg1 = args[1].(*[]int)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockAttributeRepository_List_Call) Return(attributes *[]Attribute, err error) *MockAttributeRepository_List_Call {
	_c.Call.Return(attributes, err)
	return _c
}

func (_c *MockAttributeRepository_List_Call) RunAndReturn(run func(ctx context.Context, ids *[]int, search *string, deleted string, limit int, offset int) (*[]Attribute, error)) *MockAttributeRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockAttributeRepository
func (_mock *MockAttributeRepository) Remove(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAttributeRepository_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockAttributeRepository_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockAttributeRepository_Expecter) Remove(ctx interface{}, id interface{}) *MockAttributeRepository_Remove_Call {
	return &MockAttributeRepository_Remove_Call{Call: _e.mock.On("Remove", ctx, id)}
}

func (_c *MockAttributeRepository_Remove_Call) Run(run func(ctx context.Context, id int)) *MockAttributeRepository_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttributeRepository_Remove_Call) Return(err error) *MockAttributeRepository_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAttributeRepository_Remove_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockAttributeRepository_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockAttributeRepository
func (_mock *MockAttributeRepository) Save(ctx context.Context, attribute *Attribute) (*Attribute, error) {
	ret := _mock.Called(ctx, attribute)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *Attribute
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Attribute) (*Attribute, error)); ok {
		return returnFunc(ctx, attribute)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Attribute) *Attribute); ok {
		r0 = returnFunc(ctx, attribute)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Attribute)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *Attribute) error); ok {
		r1 = returnFunc(ctx, attribute)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttributeRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAttributeRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - attribute *Attribute
func (_e *MockAttributeRepository_Expecter) Save(ctx interface{}, attribute interface{}) *MockAttributeRepository_Save_Call {
	return &MockAttributeRepository_Save_Call{Call: _e.mock.On("Save", ctx, attribute)}
}

func (_c *MockAttributeRepository_Save_Call) Run(run func(ctx context.Context, attribute *Attribute)) *MockAttributeRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Attribute
		if args[1] != nil {
			arg1 = args[1].(*Attribute)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttributeRepository_Save_Call) Return(attribute1 *Attribute, err error) *MockAttributeRepository_Save_Call {
	_c.Call.Return(attribute1, err)
	return _c
}

func (_c *MockAttributeRepository_Save_Call) RunAndReturn(run func(ctx context.Context, attribute *Attribute) (*Attribute, error)) *MockAttributeRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
