// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAttributeRepository creates a new instance of MockAttributeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttributeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttributeRepository {
	mock := &MockAttributeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAttributeRepository is an autogenerated mock type for the AttributeRepository type
type MockAttributeRepository struct {
	mock.Mock
}

type MockAttributeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttributeRepository) EXPECT() *MockAttributeRepository_Expecter {
	return &MockAttributeRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockAttributeRepository
func (_mock *MockAttributeRepository) Count(ctx context.Context, params AttributeRepositoryCountParam) (*int, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 *int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, AttributeRepositoryCountParam) (*int, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, AttributeRepositoryCountParam) *int); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, AttributeRepositoryCountParam) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttributeRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockAttributeRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - params AttributeRepositoryCountParam
func (_e *MockAttributeRepository_Expecter) Count(ctx interface{}, params interface{}) *MockAttributeRepository_Count_Call {
	return &MockAttributeRepository_Count_Call{Call: _e.mock.On("Count", ctx, params)}
}

func (_c *MockAttributeRepository_Count_Call) Run(run func(ctx context.Context, params AttributeRepositoryCountParam)) *MockAttributeRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 AttributeRepositoryCountParam
		if args[1] != nil {
			arg1 = args[1].(AttributeRepositoryCountParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttributeRepository_Count_Call) Return(n *int, err error) *MockAttributeRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAttributeRepository_Count_Call) RunAndReturn(run func(ctx context.Context, params AttributeRepositoryCountParam) (*int, error)) *MockAttributeRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// CountValues provides a mock function for the type MockAttributeRepository
func (_mock *MockAttributeRepository) CountValues(ctx context.Context, params AttributeRepositoryCountValuesParam) (*int, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CountValues")
	}

	var r0 *int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, AttributeRepositoryCountValuesParam) (*int, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, AttributeRepositoryCountValuesParam) *int); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, AttributeRepositoryCountValuesParam) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttributeRepository_CountValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountValues'
type MockAttributeRepository_CountValues_Call struct {
	*mock.Call
}

// CountValues is a helper method to define mock.On call
//   - ctx context.Context
//   - params AttributeRepositoryCountValuesParam
func (_e *MockAttributeRepository_Expecter) CountValues(ctx interface{}, params interface{}) *MockAttributeRepository_CountValues_Call {
	return &MockAttributeRepository_CountValues_Call{Call: _e.mock.On("CountValues", ctx, params)}
}

func (_c *MockAttributeRepository_CountValues_Call) Run(run func(ctx context.Context, params AttributeRepositoryCountValuesParam)) *MockAttributeRepository_CountValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 AttributeRepositoryCountValuesParam
		if args[1] != nil {
			arg1 = args[1].(AttributeRepositoryCountValuesParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttributeRepository_CountValues_Call) Return(n *int, err error) *MockAttributeRepository_CountValues_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAttributeRepository_CountValues_Call) RunAndReturn(run func(ctx context.Context, params AttributeRepositoryCountValuesParam) (*int, error)) *MockAttributeRepository_CountValues_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockAttributeRepository
func (_mock *MockAttributeRepository) Get(ctx context.Context, params AttributeRepositoryGetParam) (*Attribute, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *Attribute
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, AttributeRepositoryGetParam) (*Attribute, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, AttributeRepositoryGetParam) *Attribute); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Attribute)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, AttributeRepositoryGetParam) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttributeRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAttributeRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - params AttributeRepositoryGetParam
func (_e *MockAttributeRepository_Expecter) Get(ctx interface{}, params interface{}) *MockAttributeRepository_Get_Call {
	return &MockAttributeRepository_Get_Call{Call: _e.mock.On("Get", ctx, params)}
}

func (_c *MockAttributeRepository_Get_Call) Run(run func(ctx context.Context, params AttributeRepositoryGetParam)) *MockAttributeRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 AttributeRepositoryGetParam
		if args[1] != nil {
			arg1 = args[1].(AttributeRepositoryGetParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttributeRepository_Get_Call) Return(attribute *Attribute, err error) *MockAttributeRepository_Get_Call {
	_c.Call.Return(attribute, err)
	return _c
}

func (_c *MockAttributeRepository_Get_Call) RunAndReturn(run func(ctx context.Context, params AttributeRepositoryGetParam) (*Attribute, error)) *MockAttributeRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockAttributeRepository
func (_mock *MockAttributeRepository) List(ctx context.Context, params AttributeRepositoryListParam) (*[]Attribute, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *[]Attribute
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, AttributeRepositoryListParam) (*[]Attribute, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, AttributeRepositoryListParam) *[]Attribute); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]Attribute)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, AttributeRepositoryListParam) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttributeRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAttributeRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - params AttributeRepositoryListParam
func (_e *MockAttributeRepository_Expecter) List(ctx interface{}, params interface{}) *MockAttributeRepository_List_Call {
	return &MockAttributeRepository_List_Call{Call: _e.mock.On("List", ctx, params)}
}

func (_c *MockAttributeRepository_List_Call) Run(run func(ctx context.Context, params AttributeRepositoryListParam)) *MockAttributeRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 AttributeRepositoryListParam
		if args[1] != nil {
			arg1 = args[1].(AttributeRepositoryListParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttributeRepository_List_Call) Return(attributes *[]Attribute, err error) *MockAttributeRepository_List_Call {
	_c.Call.Return(attributes, err)
	return _c
}

func (_c *MockAttributeRepository_List_Call) RunAndReturn(run func(ctx context.Context, params AttributeRepositoryListParam) (*[]Attribute, error)) *MockAttributeRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListValues provides a mock function for the type MockAttributeRepository
func (_mock *MockAttributeRepository) ListValues(ctx context.Context, params AttributeRepositoryListValuesParam) (*[]AttributeValue, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListValues")
	}

	var r0 *[]AttributeValue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, AttributeRepositoryListValuesParam) (*[]AttributeValue, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, AttributeRepositoryListValuesParam) *[]AttributeValue); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]AttributeValue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, AttributeRepositoryListValuesParam) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttributeRepository_ListValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListValues'
type MockAttributeRepository_ListValues_Call struct {
	*mock.Call
}

// ListValues is a helper method to define mock.On call
//   - ctx context.Context
//   - params AttributeRepositoryListValuesParam
func (_e *MockAttributeRepository_Expecter) ListValues(ctx interface{}, params interface{}) *MockAttributeRepository_ListValues_Call {
	return &MockAttributeRepository_ListValues_Call{Call: _e.mock.On("ListValues", ctx, params)}
}

func (_c *MockAttributeRepository_ListValues_Call) Run(run func(ctx context.Context, params AttributeRepositoryListValuesParam)) *MockAttributeRepository_ListValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 AttributeRepositoryListValuesParam
		if args[1] != nil {
			arg1 = args[1].(AttributeRepositoryListValuesParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttributeRepository_ListValues_Call) Return(attributeValues *[]AttributeValue, err error) *MockAttributeRepository_ListValues_Call {
	_c.Call.Return(attributeValues, err)
	return _c
}

func (_c *MockAttributeRepository_ListValues_Call) RunAndReturn(run func(ctx context.Context, params AttributeRepositoryListValuesParam) (*[]AttributeValue, error)) *MockAttributeRepository_ListValues_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockAttributeRepository
func (_mock *MockAttributeRepository) Save(ctx context.Context, params AttributeRepositorySaveParam) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, AttributeRepositorySaveParam) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAttributeRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAttributeRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - params AttributeRepositorySaveParam
func (_e *MockAttributeRepository_Expecter) Save(ctx interface{}, params interface{}) *MockAttributeRepository_Save_Call {
	return &MockAttributeRepository_Save_Call{Call: _e.mock.On("Save", ctx, params)}
}

func (_c *MockAttributeRepository_Save_Call) Run(run func(ctx context.Context, params AttributeRepositorySaveParam)) *MockAttributeRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 AttributeRepositorySaveParam
		if args[1] != nil {
			arg1 = args[1].(AttributeRepositorySaveParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttributeRepository_Save_Call) Return(err error) *MockAttributeRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAttributeRepository_Save_Call) RunAndReturn(run func(ctx context.Context, params AttributeRepositorySaveParam) error) *MockAttributeRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
