// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Count(ctx context.Context, ids *[]int, deleted string, limit int, offset int) (*int, error) {
	ret := _mock.Called(ctx, ids, deleted, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 *int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]int, string, int, int) (*int, error)); ok {
		return returnFunc(ctx, ids, deleted, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]int, string, int, int) *int); ok {
		r0 = returnFunc(ctx, ids, deleted, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *[]int, string, int, int) error); ok {
		r1 = returnFunc(ctx, ids, deleted, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockOrderRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - ids *[]int
//   - deleted string
//   - limit int
//   - offset int
func (_e *MockOrderRepository_Expecter) Count(ctx interface{}, ids interface{}, deleted interface{}, limit interface{}, offset interface{}) *MockOrderRepository_Count_Call {
	return &MockOrderRepository_Count_Call{Call: _e.mock.On("Count", ctx, ids, deleted, limit, offset)}
}

func (_c *MockOrderRepository_Count_Call) Run(run func(ctx context.Context, ids *[]int, deleted string, limit int, offset int)) *MockOrderRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *[]int
		if args[1] != nil {
			arg1 = args[1].(*[]int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Count_Call) Return(n *int, err error) *MockOrderRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockOrderRepository_Count_Call) RunAndReturn(run func(ctx context.Context, ids *[]int, deleted string, limit int, offset int) (*int, error)) *MockOrderRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Get(ctx context.Context, id int) (*Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockOrderRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockOrderRepository_Expecter) Get(ctx interface{}, id interface{}) *MockOrderRepository_Get_Call {
	return &MockOrderRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockOrderRepository_Get_Call) Run(run func(ctx context.Context, id int)) *MockOrderRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Get_Call) Return(order *Order, err error) *MockOrderRepository_Get_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id int) (*Order, error)) *MockOrderRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) List(ctx context.Context, ids *[]int, search *string, deleted string, limit int, offset int) (*[]Order, error) {
	ret := _mock.Called(ctx, ids, search, deleted, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *[]Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]int, *string, string, int, int) (*[]Order, error)); ok {
		return returnFunc(ctx, ids, search, deleted, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]int, *string, string, int, int) *[]Order); ok {
		r0 = returnFunc(ctx, ids, search, deleted, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *[]int, *string, string, int, int) error); ok {
		r1 = returnFunc(ctx, ids, search, deleted, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockOrderRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - ids *[]int
//   - search *string
//   - deleted string
//   - limit int
//   - offset int
func (_e *MockOrderRepository_Expecter) List(ctx interface{}, ids interface{}, search interface{}, deleted interface{}, limit interface{}, offset interface{}) *MockOrderRepository_List_Call {
	return &MockOrderRepository_List_Call{Call: _e.mock.On("List", ctx, ids, search, deleted, limit, offset)}
}

func (_c *MockOrderRepository_List_Call) Run(run func(ctx context.Context, ids *[]int, search *string, deleted string, limit int, offset int)) *MockOrderRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *[]int
		if args[1] != nil {
			arg1 = args[1].(*[]int)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockOrderRepository_List_Call) Return(orders *[]Order, err error) *MockOrderRepository_List_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderRepository_List_Call) RunAndReturn(run func(ctx context.Context, ids *[]int, search *string, deleted string, limit int, offset int) (*[]Order, error)) *MockOrderRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Remove(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockOrderRepository_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockOrderRepository_Expecter) Remove(ctx interface{}, id interface{}) *MockOrderRepository_Remove_Call {
	return &MockOrderRepository_Remove_Call{Call: _e.mock.On("Remove", ctx, id)}
}

func (_c *MockOrderRepository_Remove_Call) Run(run func(ctx context.Context, id int)) *MockOrderRepository_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Remove_Call) Return(err error) *MockOrderRepository_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_Remove_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockOrderRepository_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Save(ctx context.Context, order *Order) (*Order, error) {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Order) (*Order, error)); ok {
		return returnFunc(ctx, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Order) *Order); ok {
		r0 = returnFunc(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *Order) error); ok {
		r1 = returnFunc(ctx, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockOrderRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - order *Order
func (_e *MockOrderRepository_Expecter) Save(ctx interface{}, order interface{}) *MockOrderRepository_Save_Call {
	return &MockOrderRepository_Save_Call{Call: _e.mock.On("Save", ctx, order)}
}

func (_c *MockOrderRepository_Save_Call) Run(run func(ctx context.Context, order *Order)) *MockOrderRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Order
		if args[1] != nil {
			arg1 = args[1].(*Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Save_Call) Return(order1 *Order, err error) *MockOrderRepository_Save_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *MockOrderRepository_Save_Call) RunAndReturn(run func(ctx context.Context, order *Order) (*Order, error)) *MockOrderRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
