// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Count(ctx context.Context, params OrderRepositoryCountParam) (*int, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 *int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, OrderRepositoryCountParam) (*int, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, OrderRepositoryCountParam) *int); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, OrderRepositoryCountParam) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockOrderRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - params OrderRepositoryCountParam
func (_e *MockOrderRepository_Expecter) Count(ctx interface{}, params interface{}) *MockOrderRepository_Count_Call {
	return &MockOrderRepository_Count_Call{Call: _e.mock.On("Count", ctx, params)}
}

func (_c *MockOrderRepository_Count_Call) Run(run func(ctx context.Context, params OrderRepositoryCountParam)) *MockOrderRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 OrderRepositoryCountParam
		if args[1] != nil {
			arg1 = args[1].(OrderRepositoryCountParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Count_Call) Return(n *int, err error) *MockOrderRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockOrderRepository_Count_Call) RunAndReturn(run func(ctx context.Context, params OrderRepositoryCountParam) (*int, error)) *MockOrderRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Get(ctx context.Context, params OrderRepositoryGetParam) (*Order, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, OrderRepositoryGetParam) (*Order, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, OrderRepositoryGetParam) *Order); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, OrderRepositoryGetParam) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockOrderRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - params OrderRepositoryGetParam
func (_e *MockOrderRepository_Expecter) Get(ctx interface{}, params interface{}) *MockOrderRepository_Get_Call {
	return &MockOrderRepository_Get_Call{Call: _e.mock.On("Get", ctx, params)}
}

func (_c *MockOrderRepository_Get_Call) Run(run func(ctx context.Context, params OrderRepositoryGetParam)) *MockOrderRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 OrderRepositoryGetParam
		if args[1] != nil {
			arg1 = args[1].(OrderRepositoryGetParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Get_Call) Return(order *Order, err error) *MockOrderRepository_Get_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepository_Get_Call) RunAndReturn(run func(ctx context.Context, params OrderRepositoryGetParam) (*Order, error)) *MockOrderRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) List(ctx context.Context, params OrderRepositoryListParam) (*[]Order, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *[]Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, OrderRepositoryListParam) (*[]Order, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, OrderRepositoryListParam) *[]Order); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, OrderRepositoryListParam) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockOrderRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - params OrderRepositoryListParam
func (_e *MockOrderRepository_Expecter) List(ctx interface{}, params interface{}) *MockOrderRepository_List_Call {
	return &MockOrderRepository_List_Call{Call: _e.mock.On("List", ctx, params)}
}

func (_c *MockOrderRepository_List_Call) Run(run func(ctx context.Context, params OrderRepositoryListParam)) *MockOrderRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 OrderRepositoryListParam
		if args[1] != nil {
			arg1 = args[1].(OrderRepositoryListParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_List_Call) Return(orders *[]Order, err error) *MockOrderRepository_List_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderRepository_List_Call) RunAndReturn(run func(ctx context.Context, params OrderRepositoryListParam) (*[]Order, error)) *MockOrderRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Save(ctx context.Context, params OrderRepositorySaveParam) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, OrderRepositorySaveParam) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockOrderRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - params OrderRepositorySaveParam
func (_e *MockOrderRepository_Expecter) Save(ctx interface{}, params interface{}) *MockOrderRepository_Save_Call {
	return &MockOrderRepository_Save_Call{Call: _e.mock.On("Save", ctx, params)}
}

func (_c *MockOrderRepository_Save_Call) Run(run func(ctx context.Context, params OrderRepositorySaveParam)) *MockOrderRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 OrderRepositorySaveParam
		if args[1] != nil {
			arg1 = args[1].(OrderRepositorySaveParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Save_Call) Return(err error) *MockOrderRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_Save_Call) RunAndReturn(run func(ctx context.Context, params OrderRepositorySaveParam) error) *MockOrderRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
