// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReviewRepository creates a new instance of MockReviewRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviewRepository {
	mock := &MockReviewRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReviewRepository is an autogenerated mock type for the ReviewRepository type
type MockReviewRepository struct {
	mock.Mock
}

type MockReviewRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviewRepository) EXPECT() *MockReviewRepository_Expecter {
	return &MockReviewRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockReviewRepository
func (_mock *MockReviewRepository) Count(ctx context.Context, orderItemIDs *[]uuid.UUID, productVariantID *uuid.UUID, userIDs *[]uuid.UUID, deleted DeletedParam) (*int, error) {
	ret := _mock.Called(ctx, orderItemIDs, productVariantID, userIDs, deleted)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 *int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]uuid.UUID, *uuid.UUID, *[]uuid.UUID, DeletedParam) (*int, error)); ok {
		return returnFunc(ctx, orderItemIDs, productVariantID, userIDs, deleted)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]uuid.UUID, *uuid.UUID, *[]uuid.UUID, DeletedParam) *int); ok {
		r0 = returnFunc(ctx, orderItemIDs, productVariantID, userIDs, deleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *[]uuid.UUID, *uuid.UUID, *[]uuid.UUID, DeletedParam) error); ok {
		r1 = returnFunc(ctx, orderItemIDs, productVariantID, userIDs, deleted)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockReviewRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - orderItemIDs *[]uuid.UUID
//   - productVariantID *uuid.UUID
//   - userIDs *[]uuid.UUID
//   - deleted DeletedParam
func (_e *MockReviewRepository_Expecter) Count(ctx interface{}, orderItemIDs interface{}, productVariantID interface{}, userIDs interface{}, deleted interface{}) *MockReviewRepository_Count_Call {
	return &MockReviewRepository_Count_Call{Call: _e.mock.On("Count", ctx, orderItemIDs, productVariantID, userIDs, deleted)}
}

func (_c *MockReviewRepository_Count_Call) Run(run func(ctx context.Context, orderItemIDs *[]uuid.UUID, productVariantID *uuid.UUID, userIDs *[]uuid.UUID, deleted DeletedParam)) *MockReviewRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *[]uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(*[]uuid.UUID)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		var arg3 *[]uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(*[]uuid.UUID)
		}
		var arg4 DeletedParam
		if args[4] != nil {
			arg4 = args[4].(DeletedParam)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockReviewRepository_Count_Call) Return(n *int, err error) *MockReviewRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockReviewRepository_Count_Call) RunAndReturn(run func(ctx context.Context, orderItemIDs *[]uuid.UUID, productVariantID *uuid.UUID, userIDs *[]uuid.UUID, deleted DeletedParam) (*int, error)) *MockReviewRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockReviewRepository
func (_mock *MockReviewRepository) Get(ctx context.Context, id uuid.UUID) (*Review, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*Review, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *Review); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockReviewRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockReviewRepository_Expecter) Get(ctx interface{}, id interface{}) *MockReviewRepository_Get_Call {
	return &MockReviewRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockReviewRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockReviewRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewRepository_Get_Call) Return(review *Review, err error) *MockReviewRepository_Get_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockReviewRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*Review, error)) *MockReviewRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockReviewRepository
func (_mock *MockReviewRepository) List(ctx context.Context, orderItemIDs *[]uuid.UUID, productVariantID *uuid.UUID, userIDs *[]uuid.UUID, deleted DeletedParam, limit int, offset int) (*[]Review, error) {
	ret := _mock.Called(ctx, orderItemIDs, productVariantID, userIDs, deleted, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *[]Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]uuid.UUID, *uuid.UUID, *[]uuid.UUID, DeletedParam, int, int) (*[]Review, error)); ok {
		return returnFunc(ctx, orderItemIDs, productVariantID, userIDs, deleted, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]uuid.UUID, *uuid.UUID, *[]uuid.UUID, DeletedParam, int, int) *[]Review); ok {
		r0 = returnFunc(ctx, orderItemIDs, productVariantID, userIDs, deleted, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *[]uuid.UUID, *uuid.UUID, *[]uuid.UUID, DeletedParam, int, int) error); ok {
		r1 = returnFunc(ctx, orderItemIDs, productVariantID, userIDs, deleted, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockReviewRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - orderItemIDs *[]uuid.UUID
//   - productVariantID *uuid.UUID
//   - userIDs *[]uuid.UUID
//   - deleted DeletedParam
//   - limit int
//   - offset int
func (_e *MockReviewRepository_Expecter) List(ctx interface{}, orderItemIDs interface{}, productVariantID interface{}, userIDs interface{}, deleted interface{}, limit interface{}, offset interface{}) *MockReviewRepository_List_Call {
	return &MockReviewRepository_List_Call{Call: _e.mock.On("List", ctx, orderItemIDs, productVariantID, userIDs, deleted, limit, offset)}
}

func (_c *MockReviewRepository_List_Call) Run(run func(ctx context.Context, orderItemIDs *[]uuid.UUID, productVariantID *uuid.UUID, userIDs *[]uuid.UUID, deleted DeletedParam, limit int, offset int)) *MockReviewRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *[]uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(*[]uuid.UUID)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		var arg3 *[]uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(*[]uuid.UUID)
		}
		var arg4 DeletedParam
		if args[4] != nil {
			arg4 = args[4].(DeletedParam)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		var arg6 int
		if args[6] != nil {
			arg6 = args[6].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockReviewRepository_List_Call) Return(reviews *[]Review, err error) *MockReviewRepository_List_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockReviewRepository_List_Call) RunAndReturn(run func(ctx context.Context, orderItemIDs *[]uuid.UUID, productVariantID *uuid.UUID, userIDs *[]uuid.UUID, deleted DeletedParam, limit int, offset int) (*[]Review, error)) *MockReviewRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockReviewRepository
func (_mock *MockReviewRepository) Remove(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReviewRepository_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockReviewRepository_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockReviewRepository_Expecter) Remove(ctx interface{}, id interface{}) *MockReviewRepository_Remove_Call {
	return &MockReviewRepository_Remove_Call{Call: _e.mock.On("Remove", ctx, id)}
}

func (_c *MockReviewRepository_Remove_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockReviewRepository_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewRepository_Remove_Call) Return(err error) *MockReviewRepository_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReviewRepository_Remove_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockReviewRepository_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockReviewRepository
func (_mock *MockReviewRepository) Save(ctx context.Context, review *Review) (*Review, error) {
	ret := _mock.Called(ctx, review)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Review) (*Review, error)); ok {
		return returnFunc(ctx, review)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Review) *Review); ok {
		r0 = returnFunc(ctx, review)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *Review) error); ok {
		r1 = returnFunc(ctx, review)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockReviewRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - review *Review
func (_e *MockReviewRepository_Expecter) Save(ctx interface{}, review interface{}) *MockReviewRepository_Save_Call {
	return &MockReviewRepository_Save_Call{Call: _e.mock.On("Save", ctx, review)}
}

func (_c *MockReviewRepository_Save_Call) Run(run func(ctx context.Context, review *Review)) *MockReviewRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Review
		if args[1] != nil {
			arg1 = args[1].(*Review)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewRepository_Save_Call) Return(review1 *Review, err error) *MockReviewRepository_Save_Call {
	_c.Call.Return(review1, err)
	return _c
}

func (_c *MockReviewRepository_Save_Call) RunAndReturn(run func(ctx context.Context, review *Review) (*Review, error)) *MockReviewRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
