name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  gen-migration:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      committed: ${{ steps.add-and-commit.outputs.committed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: ariga/setup-atlas@v0
      - uses: extractions/setup-just@v3
      - name: gen migration
        run: just atlas-gen-migration
      - uses: EndBug/add-and-commit@v9
        id: add-and-commit
        with:
          add: migration/
          message: |-
            build(migration): update migration
            [skip ci]

  build-migrate:
    runs-on: ubuntu-latest
    needs:
      - gen-migration
    if: needs.gen-migration.outputs.committed == 'true'
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get commit hash
        id: commit-hash
        working-directory: .
        run: echo "commit=$(git rev-parse HEAD)" >>"${GITHUB_OUTPUT}"

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/migrate.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/migrate:latest
            ghcr.io/${{ github.repository_owner }}/migrate:${{ steps.commit-hash.outputs.commit }}
            ghcr.io/${{ github.repository_owner }}/migrate:${{ github.ref_name }}

  build-backend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get commit hash
        id: commit-hash
        working-directory: .
        run: echo "commit=$(git rev-parse HEAD)" >>"${GITHUB_OUTPUT}"

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/backend.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.commit-hash.outputs.commit }}
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}

  update-kube:
    runs-on: ubuntu-latest
    needs:
      - build-migrate
      - build-backend
    if: |
      (needs.build-backend.result == 'success') &&
      (needs.build-migrate.result == 'success' || needs.build-migrate.result == 'skipped')
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v2
        with:
          private-key: ${{ secrets.ELECTRICILIES_BOT_PRIVATE_KEY }}
          app-id: ${{ vars.ELECTRICILIES_BOT_APP_ID }}
          owner: ${{ github.repository_owner }}
          repositories: kubernetes-manifest
      - name: Trigger Renovate
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.get_token.outputs.token }}
          repository: ${{ github.repository_owner }}/kubernetes-manifest
          event-type: renovate
          client-payload: |- # language: json
            {
              "images": "ghcr.io/${{ github.repository }},ghcr.io/${{ github.repository_owner }}/migrate"
            }
