name: Sonar
on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - go.mod
      - go.sum
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "**.go"
      - go.mod
      - go.sum

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
